/**
 * ============================================================================
 * OFFENSIVE SECURITY ACADEMY - CANONICAL LESSON REGISTRY (v3.1)
 * ============================================================================
 * Programmatically derived from data/academy JSONs and curriculum-manifest.json.
 * 100% manifest parity: 27 modules / 81 lessons.
 * All lessons currently hold unverified status awaiting individual contract certification.
 */

import type { RuntimeMode } from '../types/contract';

export interface LessonDescriptor {
  id: string;
  slug: string;
  moduleId: string;
  trackId: string;
  title: string;
  runtimeMode: RuntimeMode;
  prerequisites: string[];
  validationStatus: 'draft' | 'unverified' | 'validated';
  contractVersion?: 'v3.0';
}

export const CANONICAL_LESSON_REGISTRY: Record<string, LessonDescriptor> = {
  'os00-l07-evidence-collection-and-chain-of-custody': {
    id: 'os00-l07-evidence-collection-and-chain-of-custody',
    slug: 'evidence-collection-and-chain-of-custody',
    moduleId: 'os00-m03-evidence-and-disclosure',
    trackId: 'os00-ethics-authorization',
    title: 'Thu thập Bằng chứng Kỹ thuật & Chuỗi Hành trình (Chain of Custody)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os00-l08-sensitive-data-handling-and-redaction': {
    id: 'os00-l08-sensitive-data-handling-and-redaction',
    slug: 'sensitive-data-handling-and-redaction',
    moduleId: 'os00-m03-evidence-and-disclosure',
    trackId: 'os00-ethics-authorization',
    title: 'Xử lý Dữ liệu Nhạy cảm, Che mờ (Redaction) & Lưu trữ An toàn',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l07-evidence-collection-and-chain-of-custody'],
    validationStatus: 'unverified',
  },
  'os00-l09-coordinated-vulnerability-disclosure': {
    id: 'os00-l09-coordinated-vulnerability-disclosure',
    slug: 'coordinated-vulnerability-disclosure',
    moduleId: 'os00-m03-evidence-and-disclosure',
    trackId: 'os00-ethics-authorization',
    title: 'Quy trình Công bố Lỗ hổng Phối hợp (CVD) & Quản trị Rủi ro',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l08-sensitive-data-handling-and-redaction'],
    validationStatus: 'unverified',
  },
  'os00-l01-offensive-work-map': {
    id: 'os00-l01-offensive-work-map',
    slug: 'offensive-work-map',
    moduleId: 'os00-m01-roles-and-boundaries',
    trackId: 'os00-ethics-authorization',
    title: 'Bản đồ nghề Offensive Security',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os00-l02-authority-before-capability': {
    id: 'os00-l02-authority-before-capability',
    slug: 'authority-before-capability',
    moduleId: 'os00-m01-roles-and-boundaries',
    trackId: 'os00-ethics-authorization',
    title: 'Authority trước Capability',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l01-offensive-work-map'],
    validationStatus: 'unverified',
  },
  'os00-l03-safe-harbor-decision': {
    id: 'os00-l03-safe-harbor-decision',
    slug: 'safe-harbor-decision',
    moduleId: 'os00-m01-roles-and-boundaries',
    trackId: 'os00-ethics-authorization',
    title: 'Safe Harbor không phải giấy phép vô hạn',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l02-authority-before-capability'],
    validationStatus: 'unverified',
  },
  'os00-l04-scoping-boundaries-and-dependencies': {
    id: 'os00-l04-scoping-boundaries-and-dependencies',
    slug: 'scoping-boundaries-and-dependencies',
    moduleId: 'os00-m02-rules-of-engagement',
    trackId: 'os00-ethics-authorization',
    title: 'Thiết lập Phạm vi (Scope) & Ranh giới Phụ thuộc Bên thứ ba',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os00-l05-rules-of-engagement-and-stop-conditions': {
    id: 'os00-l05-rules-of-engagement-and-stop-conditions',
    slug: 'rules-of-engagement-and-stop-conditions',
    moduleId: 'os00-m02-rules-of-engagement',
    trackId: 'os00-ethics-authorization',
    title: 'Xây dựng Rules of Engagement & Điều kiện Dừng Khẩn cấp',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l04-scoping-boundaries-and-dependencies'],
    validationStatus: 'unverified',
  },
  'os00-l06-deconfliction-and-operational-logging': {
    id: 'os00-l06-deconfliction-and-operational-logging',
    slug: 'deconfliction-and-operational-logging',
    moduleId: 'os00-m02-rules-of-engagement',
    trackId: 'os00-ethics-authorization',
    title: 'Quy trình Deconfliction, Phối hợp Tác chiến & Nhật ký Audit',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l05-rules-of-engagement-and-stop-conditions'],
    validationStatus: 'unverified',
  },
  'os01-l07-dns-resolution-and-dhcp-boundaries': {
    id: 'os01-l07-dns-resolution-and-dhcp-boundaries',
    slug: 'dns-resolution-and-dhcp-boundaries',
    moduleId: 'os01-m03-dns-transport-and-tls',
    trackId: 'os01-network-foundations',
    title: 'Phân giải DNS Phân cấp & Ranh giới Tin cậy DHCP',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l08-tcp-udp-transport-state': {
    id: 'os01-l08-tcp-udp-transport-state',
    slug: 'tcp-udp-transport-state',
    moduleId: 'os01-m03-dns-transport-and-tls',
    trackId: 'os01-network-foundations',
    title: 'Trạng Thái Transport: TCP Handshake, UDP & Khai thác Trạng thái',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l07-dns-resolution-and-dhcp-boundaries'],
    validationStatus: 'unverified',
  },
  'os01-l09-http-tls-trust-boundaries': {
    id: 'os01-l09-http-tls-trust-boundaries',
    slug: 'http-tls-trust-boundaries',
    moduleId: 'os01-m03-dns-transport-and-tls',
    trackId: 'os01-network-foundations',
    title: 'HTTP Semantics & Ranh giới Tin cậy TLS',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l08-tcp-udp-transport-state'],
    validationStatus: 'unverified',
  },
  'os01-l10-smb-ldap-enterprise-protocols': {
    id: 'os01-l10-smb-ldap-enterprise-protocols',
    slug: 'smb-ldap-enterprise-protocols',
    moduleId: 'os01-m04-enterprise-protocols-and-packets',
    trackId: 'os01-network-foundations',
    title: 'SMB & LDAP: Giao thức Chia sẻ và Thư mục của Doanh nghiệp',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l11-packet-capture-methodology': {
    id: 'os01-l11-packet-capture-methodology',
    slug: 'packet-capture-methodology',
    moduleId: 'os01-m04-enterprise-protocols-and-packets',
    trackId: 'os01-network-foundations',
    title: 'Bắt & Phân tích Gói tin: Phương pháp Có kỷ luật',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l10-smb-ldap-enterprise-protocols'],
    validationStatus: 'unverified',
  },
  'os01-l12-topology-reasoning-from-evidence': {
    id: 'os01-l12-topology-reasoning-from-evidence',
    slug: 'topology-reasoning-from-evidence',
    moduleId: 'os01-m04-enterprise-protocols-and-packets',
    trackId: 'os01-network-foundations',
    title: 'Suy luận Topology: Dựng Bản đồ Mạng từ Bằng chứng',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l11-packet-capture-methodology'],
    validationStatus: 'unverified',
  },
  'os01-l04-ethernet-and-arp-trust-boundary': {
    id: 'os01-l04-ethernet-and-arp-trust-boundary',
    slug: 'ethernet-and-arp-trust-boundary',
    moduleId: 'os01-m02-link-routing-and-segmentation',
    trackId: 'os01-network-foundations',
    title: 'Ethernet Frame, Bảng MAC của Switch & Ranh giới Tin cậy ARP',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l05-ip-routing-and-nat-boundaries': {
    id: 'os01-l05-ip-routing-and-nat-boundaries',
    slug: 'ip-routing-and-nat-boundaries',
    moduleId: 'os01-m02-link-routing-and-segmentation',
    trackId: 'os01-network-foundations',
    title: 'Bảng Định tuyến, Longest Prefix Match & Ranh giới NAT',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l04-ethernet-and-arp-trust-boundary'],
    validationStatus: 'unverified',
  },
  'os01-l06-vlan-vpn-segmentation': {
    id: 'os01-l06-vlan-vpn-segmentation',
    slug: 'vlan-vpn-segmentation',
    moduleId: 'os01-m02-link-routing-and-segmentation',
    trackId: 'os01-network-foundations',
    title: 'Phân Đoạn VLAN, Inter-VLAN Routing & Ranh giới VPN',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l05-ip-routing-and-nat-boundaries'],
    validationStatus: 'unverified',
  },
  'os01-l01-process-memory-and-data-representation': {
    id: 'os01-l01-process-memory-and-data-representation',
    slug: 'process-memory-and-data-representation',
    moduleId: 'os01-m01-processes-data-and-addressing',
    trackId: 'os01-network-foundations',
    title: 'Tiến trình (Process), Bộ nhớ & Biểu diễn Dữ liệu (Hex, Endian, Encoding)',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l02-ipv4-addressing-and-cidr-subnetting': {
    id: 'os01-l02-ipv4-addressing-and-cidr-subnetting',
    slug: 'ipv4-addressing-and-cidr-subnetting',
    moduleId: 'os01-m01-processes-data-and-addressing',
    trackId: 'os01-network-foundations',
    title: 'Địa chỉ IPv4, Phân lớp Mạng & Kỹ thuật Chia mạng con CIDR',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l01-process-memory-and-data-representation'],
    validationStatus: 'unverified',
  },
  'os01-l03-ipv6-foundations-and-dual-stack-boundaries': {
    id: 'os01-l03-ipv6-foundations-and-dual-stack-boundaries',
    slug: 'ipv6-foundations-and-dual-stack-boundaries',
    moduleId: 'os01-m01-processes-data-and-addressing',
    trackId: 'os01-network-foundations',
    title: 'Nền tảng IPv6, Ranh giới Dual-Stack & Bẫy Cấu hình An ninh',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l02-ipv4-addressing-and-cidr-subnetting'],
    validationStatus: 'unverified',
  },
  'os02-l13-filesystem-hierarchy-and-file-types': {
    id: 'os02-l13-filesystem-hierarchy-and-file-types',
    slug: 'filesystem-hierarchy-and-file-types',
    moduleId: 'os02-m01-files-identity-permissions',
    trackId: 'os02-linux-foundations',
    title: 'Cây Filesystem, Inode & Các Loại File',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os02-l14-users-groups-and-identity-boundaries': {
    id: 'os02-l14-users-groups-and-identity-boundaries',
    slug: 'users-groups-and-identity-boundaries',
    moduleId: 'os02-m01-files-identity-permissions',
    trackId: 'os02-linux-foundations',
    title: 'UID/GID, /etc/passwd–shadow & Ranh giới root/sudo',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l13-filesystem-hierarchy-and-file-types'],
    validationStatus: 'unverified',
  },
  'os02-l15-permission-bits-and-special-modes': {
    id: 'os02-l15-permission-bits-and-special-modes',
    slug: 'permission-bits-and-special-modes',
    moduleId: 'os02-m01-files-identity-permissions',
    trackId: 'os02-linux-foundations',
    title: 'Permission Bits, Umask & SUID/SGID/Sticky',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l14-users-groups-and-identity-boundaries'],
    validationStatus: 'unverified',
  },
  'os02-l19-linux-capabilities-and-suid-privesc': {
    id: 'os02-l19-linux-capabilities-and-suid-privesc',
    slug: 'linux-capabilities-and-suid-privesc',
    moduleId: 'os02-m03-linux-boundaries-and-telemetry',
    trackId: 'os02-linux-foundations',
    title: 'Linux Capabilities, SUID & Privilege Boundaries',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os02-l20-namespaces-cgroups-container-boundaries': {
    id: 'os02-l20-namespaces-cgroups-container-boundaries',
    slug: 'namespaces-cgroups-container-boundaries',
    moduleId: 'os02-m03-linux-boundaries-and-telemetry',
    trackId: 'os02-linux-foundations',
    title: 'Namespaces, Cgroups & Container Boundary Escapes',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l19-linux-capabilities-and-suid-privesc'],
    validationStatus: 'unverified',
  },
  'os02-l21-auditd-ebpf-and-host-telemetry': {
    id: 'os02-l21-auditd-ebpf-and-host-telemetry',
    slug: 'auditd-ebpf-and-host-telemetry',
    moduleId: 'os02-m03-linux-boundaries-and-telemetry',
    trackId: 'os02-linux-foundations',
    title: 'Auditd, eBPF & Linux Host Telemetry',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l20-namespaces-cgroups-container-boundaries'],
    validationStatus: 'unverified',
  },
  'os02-l16-processes-signals-and-procfs': {
    id: 'os02-l16-processes-signals-and-procfs',
    slug: 'processes-signals-and-procfs',
    moduleId: 'os02-m02-processes-services-shell',
    trackId: 'os02-linux-foundations',
    title: 'Process Tree, Signals & /proc',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os02-l17-systemd-units-and-journal': {
    id: 'os02-l17-systemd-units-and-journal',
    slug: 'systemd-units-and-journal',
    moduleId: 'os02-m02-processes-services-shell',
    trackId: 'os02-linux-foundations',
    title: 'systemd Units, Hardening Directives & Journal',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l16-processes-signals-and-procfs'],
    validationStatus: 'unverified',
  },
  'os02-l18-packages-cron-and-shell-env': {
    id: 'os02-l18-packages-cron-and-shell-env',
    slug: 'packages-cron-and-shell-env',
    moduleId: 'os02-m02-processes-services-shell',
    trackId: 'os02-linux-foundations',
    title: 'Package Integrity, Cron & Shell Environment',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l17-systemd-units-and-journal'],
    validationStatus: 'unverified',
  },
  'os03-l22-defender-av-edr-and-amsi': {
    id: 'os03-l22-defender-av-edr-and-amsi',
    slug: 'defender-av-edr-and-amsi',
    moduleId: 'os03-m03-endpoint-controls-and-events',
    trackId: 'os03-windows-foundations',
    title: 'Microsoft Defender, ASR & AMSI Architecture',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os03-l23-windows-firewall-and-network-boundaries': {
    id: 'os03-l23-windows-firewall-and-network-boundaries',
    slug: 'windows-firewall-and-network-boundaries',
    moduleId: 'os03-m03-endpoint-controls-and-events',
    trackId: 'os03-windows-foundations',
    title: 'Windows Firewall & Host Network Boundaries',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l22-defender-av-edr-and-amsi'],
    validationStatus: 'unverified',
  },
  'os03-l24-security-event-log-and-sysmon-telemetry': {
    id: 'os03-l24-security-event-log-and-sysmon-telemetry',
    slug: 'security-event-log-and-sysmon-telemetry',
    moduleId: 'os03-m03-endpoint-controls-and-events',
    trackId: 'os03-windows-foundations',
    title: 'Windows Event Logs, Sysmon & Telemetry Engineering',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l23-windows-firewall-and-network-boundaries'],
    validationStatus: 'unverified',
  },
  'os03-l19-services-scm-and-path-security': {
    id: 'os03-l19-services-scm-and-path-security',
    slug: 'services-scm-and-path-security',
    moduleId: 'os03-m02-services-powershell-remote',
    trackId: 'os03-windows-foundations',
    title: 'SCM, Service Registry & Path Security',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os03-l20-scheduled-tasks-and-autoruns': {
    id: 'os03-l20-scheduled-tasks-and-autoruns',
    slug: 'scheduled-tasks-and-autoruns',
    moduleId: 'os03-m02-services-powershell-remote',
    trackId: 'os03-windows-foundations',
    title: 'Task Scheduler & Bản đồ Autoruns',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l19-services-scm-and-path-security'],
    validationStatus: 'unverified',
  },
  'os03-l21-powershell-logging-and-remote-admin': {
    id: 'os03-l21-powershell-logging-and-remote-admin',
    slug: 'powershell-logging-and-remote-admin',
    moduleId: 'os03-m02-services-powershell-remote',
    trackId: 'os03-windows-foundations',
    title: 'PowerShell Logging, Execution Policy & WinRM/JEA',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l20-scheduled-tasks-and-autoruns'],
    validationStatus: 'unverified',
  },
  'os03-l16-windows-architecture-and-principals': {
    id: 'os03-l16-windows-architecture-and-principals',
    slug: 'windows-architecture-and-principals',
    moduleId: 'os03-m01-architecture-identities-acls',
    trackId: 'os03-windows-foundations',
    title: 'Kiến trúc Windows & Security Principals (SID)',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os03-l17-access-tokens-and-uac': {
    id: 'os03-l17-access-tokens-and-uac',
    slug: 'access-tokens-and-uac',
    moduleId: 'os03-m01-architecture-identities-acls',
    trackId: 'os03-windows-foundations',
    title: 'Access Token & UAC Filtered Token',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l16-windows-architecture-and-principals'],
    validationStatus: 'unverified',
  },
  'os03-l18-acls-and-permission-evaluation': {
    id: 'os03-l18-acls-and-permission-evaluation',
    slug: 'acls-and-permission-evaluation',
    moduleId: 'os03-m01-architecture-identities-acls',
    trackId: 'os03-windows-foundations',
    title: 'Security Descriptor, DACL & Thứ tự Đánh giá ACE',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l17-access-tokens-and-uac'],
    validationStatus: 'unverified',
  },
  'os04-l25-bash-scripting-and-pipeline-safety': {
    id: 'os04-l25-bash-scripting-and-pipeline-safety',
    slug: 'bash-scripting-and-pipeline-safety',
    moduleId: 'os04-m01-bash-python-powershell',
    trackId: 'os04-operator-scripting',
    title: 'Safe Bash Scripting & UNIX Pipeline Engineering',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os04-l26-python-operator-tooling-and-subprocesses': {
    id: 'os04-l26-python-operator-tooling-and-subprocesses',
    slug: 'python-operator-tooling-and-subprocesses',
    moduleId: 'os04-m01-bash-python-powershell',
    trackId: 'os04-operator-scripting',
    title: 'Python Operator Tooling & Safe Subprocess Architecture',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l25-bash-scripting-and-pipeline-safety'],
    validationStatus: 'unverified',
  },
  'os04-l27-powershell-advanced-functions-and-objects': {
    id: 'os04-l27-powershell-advanced-functions-and-objects',
    slug: 'powershell-advanced-functions-and-objects',
    moduleId: 'os04-m01-bash-python-powershell',
    trackId: 'os04-operator-scripting',
    title: 'PowerShell Advanced Functions & Object Pipeline Architecture',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l26-python-operator-tooling-and-subprocesses'],
    validationStatus: 'unverified',
  },
  'os04-l31-concurrency-asyncio-and-worker-pools': {
    id: 'os04-l31-concurrency-asyncio-and-worker-pools',
    slug: 'concurrency-asyncio-and-worker-pools',
    moduleId: 'os04-m03-safe-evidence-automation',
    trackId: 'os04-operator-scripting',
    title: 'Bounded Concurrency, AsyncIO & Worker Pool Engineering',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os04-l32-defensive-error-handling-and-telemetry-pipelines': {
    id: 'os04-l32-defensive-error-handling-and-telemetry-pipelines',
    slug: 'defensive-error-handling-and-telemetry-pipelines',
    moduleId: 'os04-m03-safe-evidence-automation',
    trackId: 'os04-operator-scripting',
    title: 'Defensive Error Architecture & Observable Telemetry Pipelines',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l31-concurrency-asyncio-and-worker-pools'],
    validationStatus: 'unverified',
  },
  'os04-l33-evidence-collector-capstone-and-safe-packaging': {
    id: 'os04-l33-evidence-collector-capstone-and-safe-packaging',
    slug: 'evidence-collector-capstone-and-safe-packaging',
    moduleId: 'os04-m03-safe-evidence-automation',
    trackId: 'os04-operator-scripting',
    title: 'Safe Operator CLI Packaging & Evidence Collector Capstone',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l32-defensive-error-handling-and-telemetry-pipelines'],
    validationStatus: 'unverified',
  },
  'os04-l28-regular-expressions-and-text-normalization': {
    id: 'os04-l28-regular-expressions-and-text-normalization',
    slug: 'regular-expressions-and-text-normalization',
    moduleId: 'os04-m02-structured-data-http-git',
    trackId: 'os04-operator-scripting',
    title: 'Deterministic Regular Expressions & Telemetry Normalization',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os04-l29-structured-data-json-yaml-csv-parsing': {
    id: 'os04-l29-structured-data-json-yaml-csv-parsing',
    slug: 'structured-data-json-yaml-csv-parsing',
    moduleId: 'os04-m02-structured-data-http-git',
    trackId: 'os04-operator-scripting',
    title: 'Type-Safe Data Serialization: JSON, YAML & CSV Ingestion',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l28-regular-expressions-and-text-normalization'],
    validationStatus: 'unverified',
  },
  'os04-l30-http-clients-and-git-automation': {
    id: 'os04-l30-http-clients-and-git-automation',
    slug: 'http-clients-and-git-automation',
    moduleId: 'os04-m02-structured-data-http-git',
    trackId: 'os04-operator-scripting',
    title: 'Resilient HTTP Clients & Secure Git Evidence Automation',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l29-structured-data-json-yaml-csv-parsing'],
    validationStatus: 'unverified',
  },
  'os05-l34-penetration-testing-standards-and-planning': {
    id: 'os05-l34-penetration-testing-standards-and-planning',
    slug: 'penetration-testing-standards-and-planning',
    moduleId: 'os05-m01-engagement-recon-enumeration',
    trackId: 'os05-pentest-methodology',
    title: 'Penetration Testing Frameworks, Scoping & Pre-Engagement Planning',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os05-l35-passive-reconnaissance-and-osint-methodology': {
    id: 'os05-l35-passive-reconnaissance-and-osint-methodology',
    slug: 'passive-reconnaissance-and-osint-methodology',
    moduleId: 'os05-m01-engagement-recon-enumeration',
    trackId: 'os05-pentest-methodology',
    title: 'Passive Reconnaissance, OSINT & Attack Surface Discovery',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l34-penetration-testing-standards-and-planning'],
    validationStatus: 'unverified',
  },
  'os05-l36-active-enumeration-and-service-fingerprinting': {
    id: 'os05-l36-active-enumeration-and-service-fingerprinting',
    slug: 'active-enumeration-and-service-fingerprinting',
    moduleId: 'os05-m01-engagement-recon-enumeration',
    trackId: 'os05-pentest-methodology',
    title: 'Active Enumeration, Service Fingerprinting & Protocol Discovery',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l35-passive-reconnaissance-and-osint-methodology'],
    validationStatus: 'unverified',
  },
  'os05-l40-technical-vulnerability-reporting-and-structure': {
    id: 'os05-l40-technical-vulnerability-reporting-and-structure',
    slug: 'technical-vulnerability-reporting-and-structure',
    moduleId: 'os05-m03-report-remediation-retest',
    trackId: 'os05-pentest-methodology',
    title: 'Professional Vulnerability Reporting & Finding Structure',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os05-l41-root-cause-analysis-and-defense-in-depth-remediation': {
    id: 'os05-l41-root-cause-analysis-and-defense-in-depth-remediation',
    slug: 'root-cause-analysis-and-defense-in-depth-remediation',
    moduleId: 'os05-m03-report-remediation-retest',
    trackId: 'os05-pentest-methodology',
    title: 'Root-Cause Remediation, Defense-in-Depth & Strategic Guidance',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l40-technical-vulnerability-reporting-and-structure'],
    validationStatus: 'unverified',
  },
  'os05-l42-remediation-verification-and-retesting-workflows': {
    id: 'os05-l42-remediation-verification-and-retesting-workflows',
    slug: 'remediation-verification-and-retesting-workflows',
    moduleId: 'os05-m03-report-remediation-retest',
    trackId: 'os05-pentest-methodology',
    title: 'Remediation Verification, Retesting Workflows & Engagement Closeout',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l41-root-cause-analysis-and-defense-in-depth-remediation'],
    validationStatus: 'unverified',
  },
  'os05-l37-vulnerability-analysis-and-false-positive-triaging': {
    id: 'os05-l37-vulnerability-analysis-and-false-positive-triaging',
    slug: 'vulnerability-analysis-and-false-positive-triaging',
    moduleId: 'os05-m02-verification-impact-evidence',
    trackId: 'os05-pentest-methodology',
    title: 'Vulnerability Analysis, CVE Mapping & False-Positive Triaging',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os05-l38-controlled-exploitation-and-proof-of-concept': {
    id: 'os05-l38-controlled-exploitation-and-proof-of-concept',
    slug: 'controlled-exploitation-and-proof-of-concept',
    moduleId: 'os05-m02-verification-impact-evidence',
    trackId: 'os05-pentest-methodology',
    title: 'Controlled Exploitation, Safe Proof of Concept & Blast Radius Management',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l37-vulnerability-analysis-and-false-positive-triaging'],
    validationStatus: 'unverified',
  },
  'os05-l39-business-impact-demonstration-and-evidence-chain': {
    id: 'os05-l39-business-impact-demonstration-and-evidence-chain',
    slug: 'business-impact-demonstration-and-evidence-chain',
    moduleId: 'os05-m02-verification-impact-evidence',
    trackId: 'os05-pentest-methodology',
    title: 'Business Impact Modeling, Data Redaction & Forensic Evidence Sealing',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l38-controlled-exploitation-and-proof-of-concept'],
    validationStatus: 'unverified',
  },
  'os06-l49-blind-network-reconnaissance-and-initial-foothold': {
    id: 'os06-l49-blind-network-reconnaissance-and-initial-foothold',
    slug: 'blind-network-reconnaissance-and-initial-foothold',
    moduleId: 'os06-m03-blind-enterprise-network',
    trackId: 'os06-network-infrastructure',
    title: 'Blind Network Triage, Passive Discovery & Initial Foothold Acquisition',
    runtimeMode: 'browser-demo',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os06-l50-multi-tier-lateral-movement-and-privilege-chains': {
    id: 'os06-l50-multi-tier-lateral-movement-and-privilege-chains',
    slug: 'multi-tier-lateral-movement-and-privilege-chains',
    moduleId: 'os06-m03-blind-enterprise-network',
    trackId: 'os06-network-infrastructure',
    title: 'Multi-Tier Lateral Movement & Enterprise Privilege Chaining',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l49-blind-network-reconnaissance-and-initial-foothold'],
    validationStatus: 'unverified',
  },
  'os06-l51-comprehensive-infrastructure-audit-and-reporting': {
    id: 'os06-l51-comprehensive-infrastructure-audit-and-reporting',
    slug: 'comprehensive-infrastructure-audit-and-reporting',
    moduleId: 'os06-m03-blind-enterprise-network',
    trackId: 'os06-network-infrastructure',
    title: 'Enterprise Attack Path Mapping, Remediation & Executive Debrief',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l50-multi-tier-lateral-movement-and-privilege-chains'],
    validationStatus: 'unverified',
  },
  'os06-l43-enterprise-network-discovery-and-smb-rpc-enumeration': {
    id: 'os06-l43-enterprise-network-discovery-and-smb-rpc-enumeration',
    slug: 'enterprise-network-discovery-and-smb-rpc-enumeration',
    moduleId: 'os06-m01-discovery-services-authentication',
    trackId: 'os06-network-infrastructure',
    title: 'Enterprise Network Discovery & SMB/RPC Protocol Interrogation',
    runtimeMode: 'browser-demo',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os06-l44-common-infrastructure-services-and-misconfigurations': {
    id: 'os06-l44-common-infrastructure-services-and-misconfigurations',
    slug: 'common-infrastructure-services-and-misconfigurations',
    moduleId: 'os06-m01-discovery-services-authentication',
    trackId: 'os06-network-infrastructure',
    title: 'Common Infrastructure Services & Misconfiguration Auditing',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l43-enterprise-network-discovery-and-smb-rpc-enumeration'],
    validationStatus: 'unverified',
  },
  'os06-l45-authentication-weaknesses-and-credential-auditing': {
    id: 'os06-l45-authentication-weaknesses-and-credential-auditing',
    slug: 'authentication-weaknesses-and-credential-auditing',
    moduleId: 'os06-m01-discovery-services-authentication',
    trackId: 'os06-network-infrastructure',
    title: 'Authentication Weaknesses & Credential Spraying Safety',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l44-common-infrastructure-services-and-misconfigurations'],
    validationStatus: 'unverified',
  },
  'os06-l46-host-privilege-boundaries-and-session-security': {
    id: 'os06-l46-host-privilege-boundaries-and-session-security',
    slug: 'host-privilege-boundaries-and-session-security',
    moduleId: 'os06-m02-host-boundaries-and-movement',
    trackId: 'os06-network-infrastructure',
    title: 'Host Privilege Boundaries & Interactive Session Containment',
    runtimeMode: 'browser-demo',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os06-l47-ssh-and-socks-pivoting-port-forwarding': {
    id: 'os06-l47-ssh-and-socks-pivoting-port-forwarding',
    slug: 'ssh-and-socks-pivoting-port-forwarding',
    moduleId: 'os06-m02-host-boundaries-and-movement',
    trackId: 'os06-network-infrastructure',
    title: 'Multi-Tier Tunneling, SOCKS Proxies & Lateral Pivoting',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l46-host-privilege-boundaries-and-session-security'],
    validationStatus: 'unverified',
  },
  'os06-l48-network-segmentation-testing-and-telemetry-evasion': {
    id: 'os06-l48-network-segmentation-testing-and-telemetry-evasion',
    slug: 'network-segmentation-testing-and-telemetry-evasion',
    moduleId: 'os06-m02-host-boundaries-and-movement',
    trackId: 'os06-network-infrastructure',
    title: 'Network Segmentation Validation & Defensive Telemetry Analysis',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l47-ssh-and-socks-pivoting-port-forwarding'],
    validationStatus: 'unverified',
  },
  'os07-l55-broken-object-level-and-function-authorization': {
    id: 'os07-l55-broken-object-level-and-function-authorization',
    slug: 'broken-object-level-and-function-authorization',
    moduleId: 'os07-m02-access-control-and-injection',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Broken Object & Function Level Authorization (BOLA/IDOR & BFLA)',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l56-cross-site-scripting-and-context-encoding': {
    id: 'os07-l56-cross-site-scripting-and-context-encoding',
    slug: 'cross-site-scripting-and-context-encoding',
    moduleId: 'os07-m02-access-control-and-injection',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Cross-Site Scripting (XSS), Contextual Encoding & Content Security Policy',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l55-broken-object-level-and-function-authorization'],
    validationStatus: 'unverified',
  },
  'os07-l57-sql-nosql-command-and-template-injection': {
    id: 'os07-l57-sql-nosql-command-and-template-injection',
    slug: 'sql-nosql-command-and-template-injection',
    moduleId: 'os07-m02-access-control-and-injection',
    trackId: 'os07-web-api-bug-bounty',
    title: 'SQL, NoSQL, OS Command & Server-Side Template Injection (SSTI)',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l56-cross-site-scripting-and-context-encoding'],
    validationStatus: 'unverified',
  },
  'os07-l64-bug-bounty-reconnaissance-and-asset-mapping': {
    id: 'os07-l64-bug-bounty-reconnaissance-and-asset-mapping',
    slug: 'bug-bounty-reconnaissance-and-asset-mapping',
    moduleId: 'os07-m05-bounty-recon-report-disclosure',
    trackId: 'os07-web-api-bug-bounty',
    title: 'External Attack Surface Management & Bug Bounty Reconnaissance',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l65-vulnerability-triage-and-cvss-v4-impact': {
    id: 'os07-l65-vulnerability-triage-and-cvss-v4-impact',
    slug: 'vulnerability-triage-and-cvss-v4-impact',
    moduleId: 'os07-m05-bounty-recon-report-disclosure',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Vulnerability Triage, CVSS v4.0 Calculation & Impact Demonstration',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l64-bug-bounty-reconnaissance-and-asset-mapping'],
    validationStatus: 'unverified',
  },
  'os07-l66-responsible-disclosure-and-platform-etiquette': {
    id: 'os07-l66-responsible-disclosure-and-platform-etiquette',
    slug: 'responsible-disclosure-and-platform-etiquette',
    moduleId: 'os07-m05-bounty-recon-report-disclosure',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Coordinated Vulnerability Disclosure (CVD), Safe Harbor & Ethics',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l65-vulnerability-triage-and-cvss-v4-impact'],
    validationStatus: 'unverified',
  },
  'os07-l58-cors-misconfigurations-and-csrf-defenses': {
    id: 'os07-l58-cors-misconfigurations-and-csrf-defenses',
    slug: 'cors-misconfigurations-and-csrf-defenses',
    moduleId: 'os07-m03-browser-cross-origin-and-files',
    trackId: 'os07-web-api-bug-bounty',
    title: 'CORS Exploitation, Origin Reflection & Anti-CSRF Architecture',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l59-server-side-request-forgery-and-cloud-metadata': {
    id: 'os07-l59-server-side-request-forgery-and-cloud-metadata',
    slug: 'server-side-request-forgery-and-cloud-metadata',
    moduleId: 'os07-m03-browser-cross-origin-and-files',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Server-Side Request Forgery (SSRF) & Cloud Metadata Exfiltration',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l58-cors-misconfigurations-and-csrf-defenses'],
    validationStatus: 'unverified',
  },
  'os07-l60-file-upload-vulnerabilities-and-path-traversal': {
    id: 'os07-l60-file-upload-vulnerabilities-and-path-traversal',
    slug: 'file-upload-vulnerabilities-and-path-traversal',
    moduleId: 'os07-m03-browser-cross-origin-and-files',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Unrestricted File Uploads, Web Shells & Path Traversal Sanitization',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l59-server-side-request-forgery-and-cloud-metadata'],
    validationStatus: 'unverified',
  },
  'os07-l52-browser-security-model-and-http-semantics': {
    id: 'os07-l52-browser-security-model-and-http-semantics',
    slug: 'browser-security-model-and-http-semantics',
    moduleId: 'os07-m01-browser-http-auth-session',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Browser Security Model, Same-Origin Policy & HTTP Semantics',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l53-authentication-mechanisms-and-password-storage': {
    id: 'os07-l53-authentication-mechanisms-and-password-storage',
    slug: 'authentication-mechanisms-and-password-storage',
    moduleId: 'os07-m01-browser-http-auth-session',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Cryptographic Password Storage & Multi-Factor Authentication',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l52-browser-security-model-and-http-semantics'],
    validationStatus: 'unverified',
  },
  'os07-l54-session-management-cookies-and-token-lifecycles': {
    id: 'os07-l54-session-management-cookies-and-token-lifecycles',
    slug: 'session-management-cookies-and-token-lifecycles',
    moduleId: 'os07-m01-browser-http-auth-session',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Session Security, Cookie Attributes & Token Lifecycles',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l53-authentication-mechanisms-and-password-storage'],
    validationStatus: 'unverified',
  },
  'os07-l61-oauth2-flows-and-jwt-security-mechanics': {
    id: 'os07-l61-oauth2-flows-and-jwt-security-mechanics',
    slug: 'oauth2-flows-and-jwt-security-mechanics',
    moduleId: 'os07-m04-modern-api-and-business-logic',
    trackId: 'os07-web-api-bug-bounty',
    title: 'OAuth 2.0 / OIDC Vulnerabilities & JSON Web Token (JWT) Exploitation',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l62-graphql-introspection-and-websocket-security': {
    id: 'os07-l62-graphql-introspection-and-websocket-security',
    slug: 'graphql-introspection-and-websocket-security',
    moduleId: 'os07-m04-modern-api-and-business-logic',
    trackId: 'os07-web-api-bug-bounty',
    title: 'GraphQL API Security & Cross-Site WebSocket Hijacking (CSWSH)',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l61-oauth2-flows-and-jwt-security-mechanics'],
    validationStatus: 'unverified',
  },
  'os07-l63-race-conditions-and-business-logic-flaws': {
    id: 'os07-l63-race-conditions-and-business-logic-flaws',
    slug: 'race-conditions-and-business-logic-flaws',
    moduleId: 'os07-m04-modern-api-and-business-logic',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Concurrency Race Conditions & Flawed Business Logic Exploitation',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l62-graphql-introspection-and-websocket-security'],
    validationStatus: 'unverified',
  },
  'os08-l67-active-directory-domains-forests-and-trust-architecture': {
    id: 'os08-l67-active-directory-domains-forests-and-trust-architecture',
    slug: 'active-directory-domains-forests-and-trust-architecture',
    moduleId: 'os08-m01-ad-architecture-protocols',
    trackId: 'os08-active-directory',
    title:
      'Kiến trúc Active Directory: Miền, Rừng, FSMO Roles, Global Catalog & Trust Architecture',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os08-l68-kerberos-authentication-mechanics-and-ticket-exchanges': {
    id: 'os08-l68-kerberos-authentication-mechanics-and-ticket-exchanges',
    slug: 'kerberos-authentication-mechanics-and-ticket-exchanges',
    moduleId: 'os08-m01-ad-architecture-protocols',
    trackId: 'os08-active-directory',
    title:
      'Cơ chế xác thực Kerberos v5: Ticket Exchanges (AS-REQ/REP, TGS), PAC & NTLMv2 Fallback',
    runtimeMode: 'decision-lab',
    prerequisites: ['os08-l67-active-directory-domains-forests-and-trust-architecture'],
    validationStatus: 'unverified',
  },
  'os08-l69-ldap-enumeration-and-active-directory-telemetry': {
    id: 'os08-l69-ldap-enumeration-and-active-directory-telemetry',
    slug: 'ldap-enumeration-and-active-directory-telemetry',
    moduleId: 'os08-m01-ad-architecture-protocols',
    trackId: 'os08-active-directory',
    title: 'Truy vấn LDAP, Phân giải Dịch vụ DNS SRV & Telemetry Sự kiện Định danh AD',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os08-l67-active-directory-domains-forests-and-trust-architecture',
      'os08-l68-kerberos-authentication-mechanics-and-ticket-exchanges',
    ],
    validationStatus: 'unverified',
  },
  'os08-l76-active-directory-telemetry-and-event-id-monitoring': {
    id: 'os08-l76-active-directory-telemetry-and-event-id-monitoring',
    slug: 'active-directory-telemetry-and-event-id-monitoring',
    moduleId: 'os08-m04-ad-detection-capstone',
    trackId: 'os08-active-directory',
    title:
      'Giám Sát Định Danh Chuyên Sâu: Windows Event Logs, Kerberos Telemetry (4768, 4769, 4771) & Truy Vết Directory Service Access (4662)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os08-l77-enterprise-active-directory-hardening-and-tiering-architecture': {
    id: 'os08-l77-enterprise-active-directory-hardening-and-tiering-architecture',
    slug: 'enterprise-active-directory-hardening-and-tiering-architecture',
    moduleId: 'os08-m04-ad-detection-capstone',
    trackId: 'os08-active-directory',
    title:
      'Hardening Hạ Tầng Doanh Nghiệp: Kiến Trúc Phân Tầng Enterprise Access Model, LAPS v2 & Quản Trị gMSA',
    runtimeMode: 'decision-lab',
    prerequisites: ['os08-l76-active-directory-telemetry-and-event-id-monitoring'],
    validationStatus: 'unverified',
  },
  'os08-l78-multi-host-enterprise-active-directory-capstone': {
    id: 'os08-l78-multi-host-enterprise-active-directory-capstone',
    slug: 'multi-host-enterprise-active-directory-capstone',
    moduleId: 'os08-m04-ad-detection-capstone',
    trackId: 'os08-active-directory',
    title:
      'Bài Tập Capstone Tổng Hợp: Điều Tra Chuỗi Tấn Công Đa Máy Chủ & Ứng Cứu Sự Cố Khẩn Cấp Rừng Active Directory',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os08-l76-active-directory-telemetry-and-event-id-monitoring',
      'os08-l77-enterprise-active-directory-hardening-and-tiering-architecture',
    ],
    validationStatus: 'unverified',
  },
  'os08-l73-active-directory-certificate-services-and-pki-architecture': {
    id: 'os08-l73-active-directory-certificate-services-and-pki-architecture',
    slug: 'active-directory-certificate-services-and-pki-architecture',
    moduleId: 'os08-m03-adcs-trust-hybrid',
    trackId: 'os08-active-directory',
    title:
      'Dịch Vụ Chứng Chỉ Active Directory (AD CS), Kiến Trúc PKI Doanh Nghiệp & Các Vector Lạm Dụng ESC (ESC1-ESC8)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os08-l74-cross-forest-trusts-and-security-boundaries': {
    id: 'os08-l74-cross-forest-trusts-and-security-boundaries',
    slug: 'cross-forest-trusts-and-security-boundaries',
    moduleId: 'os08-m03-adcs-trust-hybrid',
    trackId: 'os08-active-directory',
    title:
      'Quan Hệ Tin Cậy Rừng (Forest Trusts), Ranh Giới An Ninh & Kỹ Thuật Lạm Dụng Ủy Thác Liên Rừng',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os08-l73-active-directory-certificate-services-and-pki-architecture',
    ],
    validationStatus: 'unverified',
  },
  'os08-l75-hybrid-identity-and-azure-ad-connect-sync': {
    id: 'os08-l75-hybrid-identity-and-azure-ad-connect-sync',
    slug: 'hybrid-identity-and-azure-ad-connect-sync',
    moduleId: 'os08-m03-adcs-trust-hybrid',
    trackId: 'os08-active-directory',
    title:
      'Định Danh Hỗn Hợp (Hybrid Identity), Cơ Chế Đồng Bộ Microsoft Entra Connect & Ranh Giới On-Prem / Cloud',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os08-l73-active-directory-certificate-services-and-pki-architecture',
      'os08-l74-cross-forest-trusts-and-security-boundaries',
    ],
    validationStatus: 'unverified',
  },
  'os08-l70-ad-principals-groups-and-privileged-access': {
    id: 'os08-l70-ad-principals-groups-and-privileged-access',
    slug: 'ad-principals-groups-and-privileged-access',
    moduleId: 'os08-m02-identities-policies-paths',
    trackId: 'os08-active-directory',
    title:
      'Thực Thể Định Danh AD (Principals), Quản Trị Nhóm Đặc Quyền & Cơ Chế AdminSDHolder / SDProp',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os08-l71-group-policy-objects-and-delegation-mechanics': {
    id: 'os08-l71-group-policy-objects-and-delegation-mechanics',
    slug: 'group-policy-objects-and-delegation-mechanics',
    moduleId: 'os08-m02-identities-policies-paths',
    trackId: 'os08-active-directory',
    title:
      'Group Policy Objects (GPO), Quyền Phân Phối SYSVOL & Kỹ Thuật Ủy Thác Kerberos (Delegation Mechanics)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os08-l70-ad-principals-groups-and-privileged-access'],
    validationStatus: 'unverified',
  },
  'os08-l72-active-directory-access-control-lists-and-attack-path-graphs': {
    id: 'os08-l72-active-directory-access-control-lists-and-attack-path-graphs',
    slug: 'active-directory-access-control-lists-and-attack-path-graphs',
    moduleId: 'os08-m02-identities-policies-paths',
    trackId: 'os08-active-directory',
    title:
      'Active Directory Access Control Lists (DACLs), Kỹ Thuật DCSync & Đồ Thị Đường Đi Tấn Công (Attack Path Analysis)',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os08-l70-ad-principals-groups-and-privileged-access',
      'os08-l71-group-policy-objects-and-delegation-mechanics',
    ],
    validationStatus: 'unverified',
  },
  'os09-l88-cicd-pipeline-security-and-runner-compromise': {
    id: 'os09-l88-cicd-pipeline-security-and-runner-compromise',
    slug: 'cicd-pipeline-security-and-runner-compromise',
    moduleId: 'os09-m04-cicd-artifacts-capstone',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'An Ninh Hạ Tầng CI/CD: Khai Thác pull_request_target, Runner Takeover & Đánh Cắp OIDC Secrets',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os09-l89-software-supply-chain-and-artifact-integrity': {
    id: 'os09-l89-software-supply-chain-and-artifact-integrity',
    slug: 'software-supply-chain-and-artifact-integrity',
    moduleId: 'os09-m04-cicd-artifacts-capstone',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Bảo Vệ Chuỗi Cung Ứng Phần Mềm: Khung An Ninh SLSA, Ký Số Sigstore/Cosign, Quản Lý SBOM & Admission Verification',
    runtimeMode: 'decision-lab',
    prerequisites: ['os09-l88-cicd-pipeline-security-and-runner-compromise'],
    validationStatus: 'unverified',
  },
  'os09-l90-cloud-container-sandbox-capstone': {
    id: 'os09-l90-cloud-container-sandbox-capstone',
    slug: 'cloud-container-sandbox-capstone',
    moduleId: 'os09-m04-cicd-artifacts-capstone',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Bài Tập Capstone Đám Mây & Vùng Chứa: Chuỗi Tấn Công Phức Hợp End-to-End Từ Source Code Đến Cloud Control Plane',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os09-l88-cicd-pipeline-security-and-runner-compromise',
      'os09-l89-software-supply-chain-and-artifact-integrity',
    ],
    validationStatus: 'unverified',
  },
  'os09-l79-cloud-identity-and-access-management-models': {
    id: 'os09-l79-cloud-identity-and-access-management-models',
    slug: 'cloud-identity-and-access-management-models',
    moduleId: 'os09-m01-cloud-identity-control-plane',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Mô Hình Quản Trị Định Danh & Kiểm Soát Truy Cập Đám Mây (AWS IAM, GCP IAM & Azure RBAC)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os09-l80-temporary-credentials-sts-and-workload-identity': {
    id: 'os09-l80-temporary-credentials-sts-and-workload-identity',
    slug: 'temporary-credentials-sts-and-workload-identity',
    moduleId: 'os09-m01-cloud-identity-control-plane',
    trackId: 'os09-cloud-container-supply-chain',
    title: 'Chứng Thư Tạm Thời AWS STS & Liên Hợp Danh Tính Workload Identity Federation',
    runtimeMode: 'decision-lab',
    prerequisites: ['os09-l79-cloud-identity-and-access-management-models'],
    validationStatus: 'unverified',
  },
  'os09-l81-cloud-control-plane-privilege-escalation': {
    id: 'os09-l81-cloud-control-plane-privilege-escalation',
    slug: 'cloud-control-plane-privilege-escalation',
    moduleId: 'os09-m01-cloud-identity-control-plane',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Kỹ Thuật Kiểm Toán & Khai Thác 21 Vector Leo Thang Đặc Quyền Cloud Control Plane',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os09-l79-cloud-identity-and-access-management-models',
      'os09-l80-temporary-credentials-sts-and-workload-identity',
    ],
    validationStatus: 'unverified',
  },
  'os09-l82-cloud-storage-exfiltration-and-ransomware': {
    id: 'os09-l82-cloud-storage-exfiltration-and-ransomware',
    slug: 'cloud-storage-exfiltration-and-ransomware',
    moduleId: 'os09-m02-cloud-workloads-and-telemetry',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'An Ninh Lưu Trữ Đối Tượng Đám Mây: S3 Object Lock, Trích Xuất Dữ Liệu & Tống Tiền Mã Hóa KMS',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os09-l83-cloud-networking-vpc-peering-and-transit-gateways': {
    id: 'os09-l83-cloud-networking-vpc-peering-and-transit-gateways',
    slug: 'cloud-networking-vpc-peering-and-transit-gateways',
    moduleId: 'os09-m02-cloud-workloads-and-telemetry',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Phân Vùng Ranh Giới Mạng Đám Mây: VPC Peering, AWS Transit Gateway & AWS PrivateLink',
    runtimeMode: 'decision-lab',
    prerequisites: ['os09-l82-cloud-storage-exfiltration-and-ransomware'],
    validationStatus: 'unverified',
  },
  'os09-l84-serverless-architecture-and-cloud-telemetry-evasion': {
    id: 'os09-l84-serverless-architecture-and-cloud-telemetry-evasion',
    slug: 'serverless-architecture-and-cloud-telemetry-evasion',
    moduleId: 'os09-m02-cloud-workloads-and-telemetry',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Kiến Trúc Serverless Lambda, Kỹ Thuật Thao Túng & Lẩn Tránh Giám Sát Cloud Telemetry',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os09-l82-cloud-storage-exfiltration-and-ransomware',
      'os09-l83-cloud-networking-vpc-peering-and-transit-gateways',
    ],
    validationStatus: 'unverified',
  },
  'os09-l85-container-runtimes-namespaces-and-breakouts': {
    id: 'os09-l85-container-runtimes-namespaces-and-breakouts',
    slug: 'container-runtimes-namespaces-and-breakouts',
    moduleId: 'os09-m03-containers-kubernetes',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Kiến Trúc Container Runtime, Linux Namespaces, cgroups & Kỹ Thuật Container Breakout',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os09-l86-kubernetes-architecture-and-api-server-threats': {
    id: 'os09-l86-kubernetes-architecture-and-api-server-threats',
    slug: 'kubernetes-architecture-and-api-server-threats',
    moduleId: 'os09-m03-containers-kubernetes',
    trackId: 'os09-cloud-container-supply-chain',
    title: 'Kiến Trúc Kubernetes, Bề Mặt Tấn Công API Server & Hiểm Họa Control Plane',
    runtimeMode: 'decision-lab',
    prerequisites: ['os09-l85-container-runtimes-namespaces-and-breakouts'],
    validationStatus: 'unverified',
  },
  'os09-l87-kubernetes-rbac-workload-identity-and-admission-control': {
    id: 'os09-l87-kubernetes-rbac-workload-identity-and-admission-control',
    slug: 'kubernetes-rbac-workload-identity-and-admission-control',
    moduleId: 'os09-m03-containers-kubernetes',
    trackId: 'os09-cloud-container-supply-chain',
    title:
      'Kubernetes RBAC, Workload Identity Đám Mây & Cơ Chế Kiểm Soát Nhập Cảnh Admission Control',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os09-l85-container-runtimes-namespaces-and-breakouts',
      'os09-l86-kubernetes-architecture-and-api-server-threats',
    ],
    validationStatus: 'unverified',
  },
  'os10-l91-android-architecture-sandboxing-and-signing': {
    id: 'os10-l91-android-architecture-sandboxing-and-signing',
    slug: 'android-architecture-sandboxing-and-signing',
    moduleId: 'os10-m01-mobile-architecture-data',
    trackId: 'os10-mobile-wireless',
    title:
      'Kiến Trúc Android OS: Zygote, Phân Tách UID Sandboxing & Cơ Chế Ký Số APK/AAB v1-v4',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os10-l92-ios-architecture-mach-o-and-entitlements': {
    id: 'os10-l92-ios-architecture-mach-o-and-entitlements',
    slug: 'ios-architecture-mach-o-and-entitlements',
    moduleId: 'os10-m01-mobile-architecture-data',
    trackId: 'os10-mobile-wireless',
    title:
      'Kiến Trúc iOS: Cấu Trúc Nhị Phân Mach-O, FairPlay DRM, Code Signing & Phân Quyền Entitlements',
    runtimeMode: 'decision-lab',
    prerequisites: ['os10-l91-android-architecture-sandboxing-and-signing'],
    validationStatus: 'unverified',
  },
  'os10-l93-mobile-local-storage-keystore-and-keychain': {
    id: 'os10-l93-mobile-local-storage-keystore-and-keychain',
    slug: 'mobile-local-storage-keystore-and-keychain',
    moduleId: 'os10-m01-mobile-architecture-data',
    trackId: 'os10-mobile-wireless',
    title:
      'Kiểm Toán An Toàn Lưu Trữ Cục Bộ: Android Keystore, EncryptedSharedPreferences, iOS Keychain & SQLite Cipher',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os10-l91-android-architecture-sandboxing-and-signing',
      'os10-l92-ios-architecture-mach-o-and-entitlements',
    ],
    validationStatus: 'unverified',
  },
  'os10-l94-android-ipc-intents-broadcasts-and-content-providers': {
    id: 'os10-l94-android-ipc-intents-broadcasts-and-content-providers',
    slug: 'android-ipc-intents-broadcasts-and-content-providers',
    moduleId: 'os10-m02-mobile-ipc-runtime-api',
    trackId: 'os10-mobile-wireless',
    title:
      'Giao Tiếp Liên Tiến Trình Android: Khai Thác Intents, Broadcast Receivers, Content Providers & Binder IPC',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os10-l95-ios-ipc-url-schemes-and-universal-links': {
    id: 'os10-l95-ios-ipc-url-schemes-and-universal-links',
    slug: 'ios-ipc-url-schemes-and-universal-links',
    moduleId: 'os10-m02-mobile-ipc-runtime-api',
    trackId: 'os10-mobile-wireless',
    title:
      'Giao Tiếp Liên Tiến Trình iOS: Khai Thác Custom URL Schemes, Universal Links & XPC Services',
    runtimeMode: 'decision-lab',
    prerequisites: ['os10-l94-android-ipc-intents-broadcasts-and-content-providers'],
    validationStatus: 'unverified',
  },
  'os10-l96-mobile-webview-attacks-and-runtime-hooking': {
    id: 'os10-l96-mobile-webview-attacks-and-runtime-hooking',
    slug: 'mobile-webview-attacks-and-runtime-hooking',
    moduleId: 'os10-m02-mobile-ipc-runtime-api',
    trackId: 'os10-mobile-wireless',
    title:
      'Khai Thác Lỗ Hổng WebView Nhúng & Can Thiệp Thời Gian Thực Qua Frida Runtime Hooking',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os10-l94-android-ipc-intents-broadcasts-and-content-providers',
      'os10-l95-ios-ipc-url-schemes-and-universal-links',
    ],
    validationStatus: 'unverified',
  },
  'os10-l97-wifi-protocols-wpa2-wpa3-and-eap-exchanges': {
    id: 'os10-l97-wifi-protocols-wpa2-wpa3-and-eap-exchanges',
    slug: 'wifi-protocols-wpa2-wpa3-and-eap-exchanges',
    moduleId: 'os10-m03-wireless-auth-and-telemetry',
    trackId: 'os10-mobile-wireless',
    title:
      'Giao Thức Wi-Fi 802.11: Bắt Bắt Tay WPA2 4-Way Handshake, Tấn Công PMKID & Cơ Chế WPA3 SAE Dragonfly',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os10-l98-enterprise-wireless-radius-and-8021x-attacks': {
    id: 'os10-l98-enterprise-wireless-radius-and-8021x-attacks',
    slug: 'enterprise-wireless-radius-and-8021x-attacks',
    moduleId: 'os10-m03-wireless-auth-and-telemetry',
    trackId: 'os10-mobile-wireless',
    title:
      'Xác Thực Mạng Không Dây Doanh Nghiệp 802.1X, Giao Thức RADIUS & Tấn Công Thu Thập Chứng Thư Rogue AP',
    runtimeMode: 'decision-lab',
    prerequisites: ['os10-l97-wifi-protocols-wpa2-wpa3-and-eap-exchanges'],
    validationStatus: 'unverified',
  },
  'os10-l99-bluetooth-low-energy-and-wireless-telemetry-monitoring': {
    id: 'os10-l99-bluetooth-low-energy-and-wireless-telemetry-monitoring',
    slug: 'bluetooth-low-energy-and-wireless-telemetry-monitoring',
    moduleId: 'os10-m03-wireless-auth-and-telemetry',
    trackId: 'os10-mobile-wireless',
    title:
      'An Ninh Bluetooth Low Energy (BLE), Khai Thác GATT/GAP & Giám Sát Không Gian Mạng Vô Tuyến WIPS Telemetry',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os10-l97-wifi-protocols-wpa2-wpa3-and-eap-exchanges',
      'os10-l98-enterprise-wireless-radius-and-8021x-attacks',
    ],
    validationStatus: 'unverified',
  },
  'os11-l103-hardware-debug-interfaces-uart-jtag-and-swd': {
    id: 'os11-l103-hardware-debug-interfaces-uart-jtag-and-swd',
    slug: 'hardware-debug-interfaces-uart-jtag-and-swd',
    moduleId: 'os11-m02-debug-protocol-device-identity',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Giao Diện Gỡ Lỗi Phần Cứng: Nhận Diện Pinout UART, JTAG TAP Controller & ARM SWD Với OpenOCD',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os11-l104-serial-buses-and-chip-communications-i2c-spi': {
    id: 'os11-l104-serial-buses-and-chip-communications-i2c-spi',
    slug: 'serial-buses-and-chip-communications-i2c-spi',
    moduleId: 'os11-m02-debug-protocol-device-identity',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Đánh Chặn & Thao Túng Bus Giao Tiếp Nối Tiếp: I2C Sniffing, SPI Flash Dumping Với Flashrom & Bus Pirate',
    runtimeMode: 'decision-lab',
    prerequisites: ['os11-l103-hardware-debug-interfaces-uart-jtag-and-swd'],
    validationStatus: 'unverified',
  },
  'os11-l105-device-identity-cryptographic-coprocessors-and-iot-cloud': {
    id: 'os11-l105-device-identity-cryptographic-coprocessors-and-iot-cloud',
    slug: 'device-identity-cryptographic-coprocessors-and-iot-cloud',
    moduleId: 'os11-m02-debug-protocol-device-identity',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Ranh Giới An Ninh Định Danh Thiết Bị, Bộ Đồng Xử Lý Mật Mã (ATECC608, TPM 2.0) & Xác Thực mTLS IoT Cloud',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os11-l103-hardware-debug-interfaces-uart-jtag-and-swd',
      'os11-l104-serial-buses-and-chip-communications-i2c-spi',
    ],
    validationStatus: 'unverified',
  },
  'os11-l100-embedded-architectures-memory-and-firmware-structures': {
    id: 'os11-l100-embedded-architectures-memory-and-firmware-structures',
    slug: 'embedded-architectures-memory-and-firmware-structures',
    moduleId: 'os11-m01-embedded-firmware-boot',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Kiến Trúc Vi Xử Lý Nhúng (ARM, MIPS, RISC-V), Bản Đồ Bộ Nhớ & Định Dạng Nhị Phân Firmware',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os11-l101-firmware-extraction-analysis-and-emulation': {
    id: 'os11-l101-firmware-extraction-analysis-and-emulation',
    slug: 'firmware-extraction-analysis-and-emulation',
    moduleId: 'os11-m01-embedded-firmware-boot',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Kỹ Thuật Trích Xuất Firmware, Phân Tích Hệ Thống Tệp & Mô Phỏng Môi Trường QEMU',
    runtimeMode: 'decision-lab',
    prerequisites: ['os11-l100-embedded-architectures-memory-and-firmware-structures'],
    validationStatus: 'unverified',
  },
  'os11-l102-secure-boot-chains-and-cryptographic-updates': {
    id: 'os11-l102-secure-boot-chains-and-cryptographic-updates',
    slug: 'secure-boot-chains-and-cryptographic-updates',
    moduleId: 'os11-m01-embedded-firmware-boot',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Chuỗi Khởi Động An Toàn (Secure Boot Chain), Hardware Root of Trust & Cập Nhật Mã Hóa FOTA',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os11-l100-embedded-architectures-memory-and-firmware-structures',
      'os11-l101-firmware-extraction-analysis-and-emulation',
    ],
    validationStatus: 'unverified',
  },
  'os11-l106-industrial-control-systems-and-purdue-model-segmentation': {
    id: 'os11-l106-industrial-control-systems-and-purdue-model-segmentation',
    slug: 'industrial-control-systems-and-purdue-model-segmentation',
    moduleId: 'os11-m03-ot-safety-and-capstone',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Hệ Thống Điều Khiển Công Nghiệp ICS/SCADA & Phân Đoạn Mạng Theo Mô Hình Purdue (IEC 62443)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os11-l107-industrial-protocols-modbus-dnp3-s7comm-and-safety-instrumented-systems': {
    id: 'os11-l107-industrial-protocols-modbus-dnp3-s7comm-and-safety-instrumented-systems',
    slug: 'industrial-protocols-modbus-dnp3-s7comm-and-safety-instrumented-systems',
    moduleId: 'os11-m03-ot-safety-and-capstone',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Giao Thức Công Nghiệp (Modbus, DNP3, S7comm) & Phân Tích Hệ Thống An Toàn Chuyên Dụng SIS (Triton/Trisis)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os11-l106-industrial-control-systems-and-purdue-model-segmentation'],
    validationStatus: 'unverified',
  },
  'os11-l108-hardware-iot-and-ot-emulated-capstone': {
    id: 'os11-l108-hardware-iot-and-ot-emulated-capstone',
    slug: 'hardware-iot-and-ot-emulated-capstone',
    moduleId: 'os11-m03-ot-safety-and-capstone',
    trackId: 'os11-iot-firmware-hardware',
    title:
      'Bài Tập Capstone Toàn Diện: Chuỗi Tấn Công Từ Thiết Bị Biên IoT Đến Mạng Điều Khiển Vật Lý OT',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os11-l106-industrial-control-systems-and-purdue-model-segmentation',
      'os11-l107-industrial-protocols-modbus-dnp3-s7comm-and-safety-instrumented-systems',
    ],
    validationStatus: 'unverified',
  },
  'os12-l115-ai-model-supply-chain-and-serialization-threats': {
    id: 'os12-l115-ai-model-supply-chain-and-serialization-threats',
    slug: 'ai-model-supply-chain-and-serialization-threats',
    moduleId: 'os12-m03-ai-supply-chain-and-capstone',
    trackId: 'os12-ai-agentic-security',
    title:
      'Hiểm Họa Chuỗi Cung Ứng Mô Hình AI & Giải Mã Serialization (Pickle RCE, SafeTensors & Model Signing)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os12-l116-agentic-telemetry-monitoring-and-audit-trails': {
    id: 'os12-l116-agentic-telemetry-monitoring-and-audit-trails',
    slug: 'agentic-telemetry-monitoring-and-audit-trails',
    moduleId: 'os12-m03-ai-supply-chain-and-capstone',
    trackId: 'os12-ai-agentic-security',
    title:
      'Giám Sát Telemetry Hệ Thống Đại Lý Tự Chủ, Dấu Vết Kiểm Toán & Phát Hiện Dị Thường Hành Vi (Agentic OpenTelemetry & Token Velocity)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os12-l115-ai-model-supply-chain-and-serialization-threats'],
    validationStatus: 'unverified',
  },
  'os12-l117-autonomous-agentic-enterprise-capstone': {
    id: 'os12-l117-autonomous-agentic-enterprise-capstone',
    slug: 'autonomous-agentic-enterprise-capstone',
    moduleId: 'os12-m03-ai-supply-chain-and-capstone',
    trackId: 'os12-ai-agentic-security',
    title:
      'Capstone Tổng Hợp: Điều Tra & Phòng Thủ Chuỗi Tấn Công Đa Đại Lý AI Trong Môi Trường Doanh Nghiệp (Multi-Agent Compromise & Incident Defense)',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os12-l115-ai-model-supply-chain-and-serialization-threats',
      'os12-l116-agentic-telemetry-monitoring-and-audit-trails',
    ],
    validationStatus: 'unverified',
  },
  'os12-l109-ai-threat-modeling-owasp-top-10-llm-and-atlas': {
    id: 'os12-l109-ai-threat-modeling-owasp-top-10-llm-and-atlas',
    slug: 'ai-threat-modeling-owasp-top-10-llm-and-atlas',
    moduleId: 'os12-m01-ai-threat-model-and-injection',
    trackId: 'os12-ai-agentic-security',
    title:
      'Mô Hình Hóa Mối Đe Dọa AI: Khung MITRE ATLAS, OWASP Top 10 for LLM & NIST AI RMF',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os12-l110-direct-and-indirect-prompt-injection-mechanics': {
    id: 'os12-l110-direct-and-indirect-prompt-injection-mechanics',
    slug: 'direct-and-indirect-prompt-injection-mechanics',
    moduleId: 'os12-m01-ai-threat-model-and-injection',
    trackId: 'os12-ai-agentic-security',
    title:
      'Kỹ Thuật Tấn Công Tiêm Dữ Liệu Chỉ Thị Trực Tiếp & Gián Tiếp (Direct & Indirect Prompt Injection)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os12-l109-ai-threat-modeling-owasp-top-10-llm-and-atlas'],
    validationStatus: 'unverified',
  },
  'os12-l111-adversarial-testing-and-automated-ai-evals': {
    id: 'os12-l111-adversarial-testing-and-automated-ai-evals',
    slug: 'adversarial-testing-and-automated-ai-evals',
    moduleId: 'os12-m01-ai-threat-model-and-injection',
    trackId: 'os12-ai-agentic-security',
    title:
      'Kiểm Thử Đối Kháng AI & Đánh Giá An Toàn Tự Động (Adversarial Testing, PyRIT & Guardrails)',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os12-l109-ai-threat-modeling-owasp-top-10-llm-and-atlas',
      'os12-l110-direct-and-indirect-prompt-injection-mechanics',
    ],
    validationStatus: 'unverified',
  },
  'os12-l112-agentic-tool-execution-and-excessive-agency': {
    id: 'os12-l112-agentic-tool-execution-and-excessive-agency',
    slug: 'agentic-tool-execution-and-excessive-agency',
    moduleId: 'os12-m02-tools-rag-identity',
    trackId: 'os12-ai-agentic-security',
    title:
      'Thực Thi Công Cụ Đại Lý (Tool Execution), Bài Toán Confused Deputy & Rủi Ro Excessive Agency',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os12-l113-retrieval-augmented-generation-and-vector-db-attacks': {
    id: 'os12-l113-retrieval-augmented-generation-and-vector-db-attacks',
    slug: 'retrieval-augmented-generation-and-vector-db-attacks',
    moduleId: 'os12-m02-tools-rag-identity',
    trackId: 'os12-ai-agentic-security',
    title:
      'Giải Phẫu Kiến Trúc RAG, Tấn Công Cơ Sở Dữ Liệu Véc-tơ & Rò Rỉ Kiểm Soát Truy Cập (ACL Leakage)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os12-l112-agentic-tool-execution-and-excessive-agency'],
    validationStatus: 'unverified',
  },
  'os12-l114-agentic-identity-delegation-and-session-hijacking': {
    id: 'os12-l114-agentic-identity-delegation-and-session-hijacking',
    slug: 'agentic-identity-delegation-and-session-hijacking',
    moduleId: 'os12-m02-tools-rag-identity',
    trackId: 'os12-ai-agentic-security',
    title:
      'Quản Trị Định Danh Đại Lý AI, Ủy Quyền Phân Tầng & Nguy Cơ Chiếm Đoạt Phiên MCP / OAuth',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os12-l112-agentic-tool-execution-and-excessive-agency',
      'os12-l113-retrieval-augmented-generation-and-vector-db-attacks',
    ],
    validationStatus: 'unverified',
  },
  'os13-l127-cwe-taxonomy-and-cvss-v3-v4-scoring-metrics': {
    id: 'os13-l127-cwe-taxonomy-and-cvss-v3-v4-scoring-metrics',
    slug: 'cwe-taxonomy-and-cvss-v3-v4-scoring-metrics',
    moduleId: 'os13-m04-cve-cwe-cvss-disclosure',
    trackId: 'os13-vulnerability-research',
    title:
      'Phân Loại Điểm Yếu MITRE CWE & Hệ Thống Đo Lường Mức Độ Nghiêm Trọng CVSS v3.1 / CVSS v4.0',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os13-l128-security-advisories-and-reproduction-receipts': {
    id: 'os13-l128-security-advisories-and-reproduction-receipts',
    slug: 'security-advisories-and-reproduction-receipts',
    moduleId: 'os13-m04-cve-cwe-cvss-disclosure',
    trackId: 'os13-vulnerability-research',
    title:
      'Biên Soạn Báo Cáo Cố Vấn An Ninh (Security Advisory) & Bằng Chứng Tái Hiện Kỹ Thuật (PoC Receipts)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os13-l127-cwe-taxonomy-and-cvss-v3-v4-scoring-metrics'],
    validationStatus: 'unverified',
  },
  'os13-l129-coordinated-vulnerability-disclosure-and-cna-workflows': {
    id: 'os13-l129-coordinated-vulnerability-disclosure-and-cna-workflows',
    slug: 'coordinated-vulnerability-disclosure-and-cna-workflows',
    moduleId: 'os13-m04-cve-cwe-cvss-disclosure',
    trackId: 'os13-vulnerability-research',
    title:
      'Quy Trình Phối Hợp Công Bố Lỗ Hổng (CVD) & Vận Hành Đơn Vị Cấp Phát CVE (CNA Workflows)',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os13-l127-cwe-taxonomy-and-cvss-v3-v4-scoring-metrics',
      'os13-l128-security-advisories-and-reproduction-receipts',
    ],
    validationStatus: 'unverified',
  },
  'os13-l121-coverage-guided-fuzzing-and-harness-engineering': {
    id: 'os13-l121-coverage-guided-fuzzing-and-harness-engineering',
    slug: 'coverage-guided-fuzzing-and-harness-engineering',
    moduleId: 'os13-m02-fuzzing-crash-triage',
    trackId: 'os13-vulnerability-research',
    title:
      'Kiểm Thử Hộp Mờ Hướng Độ Bao Phủ & Kỹ Thuật Thiết Kế Fuzz Harness Hiệu Năng Cao',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os13-l122-compiler-sanitizers-asan-msan-and-ubsan': {
    id: 'os13-l122-compiler-sanitizers-asan-msan-and-ubsan',
    slug: 'compiler-sanitizers-asan-msan-and-ubsan',
    moduleId: 'os13-m02-fuzzing-crash-triage',
    trackId: 'os13-vulnerability-research',
    title: 'Bộ Khử Nhiễm Trình Biên Dịch: Kỹ Thuật Shadow Memory Với ASan, MSan & UBSan',
    runtimeMode: 'decision-lab',
    prerequisites: ['os13-l121-coverage-guided-fuzzing-and-harness-engineering'],
    validationStatus: 'unverified',
  },
  'os13-l123-crash-triage-minimization-and-deduplication': {
    id: 'os13-l123-crash-triage-minimization-and-deduplication',
    slug: 'crash-triage-minimization-and-deduplication',
    moduleId: 'os13-m02-fuzzing-crash-triage',
    trackId: 'os13-vulnerability-research',
    title: 'Phân Loại Điểm Sập, Thu Gọn Dữ Liệu Tái Hiện & Khử Trùng Lặp Tín Hiệu Lỗi',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os13-l121-coverage-guided-fuzzing-and-harness-engineering',
      'os13-l122-compiler-sanitizers-asan-msan-and-ubsan',
    ],
    validationStatus: 'unverified',
  },
  'os13-l118-vulnerability-research-methodology-and-threat-hypotheses': {
    id: 'os13-l118-vulnerability-research-methodology-and-threat-hypotheses',
    slug: 'vulnerability-research-methodology-and-threat-hypotheses',
    moduleId: 'os13-m01-research-surface-source-audit',
    trackId: 'os13-vulnerability-research',
    title: 'Phương Pháp Luận Nghiên Cứu Lỗ Hổng & Thiết Lập Giả Thuyết Mối Đe Dọa',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os13-l119-attack-surface-mapping-and-entrypoint-tracing': {
    id: 'os13-l119-attack-surface-mapping-and-entrypoint-tracing',
    slug: 'attack-surface-mapping-and-entrypoint-tracing',
    moduleId: 'os13-m01-research-surface-source-audit',
    trackId: 'os13-vulnerability-research',
    title:
      'Bản Đồ Hóa Bề Mặt Tấn Công & Truy Vết Luồng Dữ Liệu Điểm Vào (Entrypoint Tracing)',
    runtimeMode: 'decision-lab',
    prerequisites: ['os13-l118-vulnerability-research-methodology-and-threat-hypotheses'],
    validationStatus: 'unverified',
  },
  'os13-l120-static-analysis-and-manual-source-code-auditing': {
    id: 'os13-l120-static-analysis-and-manual-source-code-auditing',
    slug: 'static-analysis-and-manual-source-code-auditing',
    moduleId: 'os13-m01-research-surface-source-audit',
    trackId: 'os13-vulnerability-research',
    title:
      'Phân Tích Tĩnh AST & Kiểm Toán Mã Nguồn Thủ Công Chuyên Sâu (Manual Source Code Auditing)',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os13-l118-vulnerability-research-methodology-and-threat-hypotheses',
      'os13-l119-attack-surface-mapping-and-entrypoint-tracing',
    ],
    validationStatus: 'unverified',
  },
  'os13-l124-root-cause-analysis-and-primitive-characterization': {
    id: 'os13-l124-root-cause-analysis-and-primitive-characterization',
    slug: 'root-cause-analysis-and-primitive-characterization',
    moduleId: 'os13-m03-root-cause-variants-patches',
    trackId: 'os13-vulnerability-research',
    title:
      'Phân Tích Nguyên Nhân Gốc (RCA) & Định Tính Nguyên Thủy Khai Thác (Primitive Characterization)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os13-l125-variant-analysis-with-semgrep-and-codeql': {
    id: 'os13-l125-variant-analysis-with-semgrep-and-codeql',
    slug: 'variant-analysis-with-semgrep-and-codeql',
    moduleId: 'os13-m03-root-cause-variants-patches',
    trackId: 'os13-vulnerability-research',
    title:
      'Phân Tích Biến Thể Quy Mô Lớn: Xây Dựng Quy Tắc Semgrep & Truy Vấn Luồng Dữ Liệu CodeQL',
    runtimeMode: 'decision-lab',
    prerequisites: ['os13-l124-root-cause-analysis-and-primitive-characterization'],
    validationStatus: 'unverified',
  },
  'os13-l126-patch-diffing-and-exploitability-assessment': {
    id: 'os13-l126-patch-diffing-and-exploitability-assessment',
    slug: 'patch-diffing-and-exploitability-assessment',
    moduleId: 'os13-m03-root-cause-variants-patches',
    trackId: 'os13-vulnerability-research',
    title:
      'So Sánh Bản Vá Nhị Phân (Binary Patch Diffing) & Đánh Giá Khả Năng Khai Thác (Exploitability Assessment)',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os13-l124-root-cause-analysis-and-primitive-characterization',
      'os13-l125-variant-analysis-with-semgrep-and-codeql',
    ],
    validationStatus: 'unverified',
  },
  'os14-l130-memory-layout-stack-heap-and-calling-conventions': {
    id: 'os14-l130-memory-layout-stack-heap-and-calling-conventions',
    slug: 'memory-layout-stack-heap-and-calling-conventions',
    moduleId: 'os14-m01-memory-assembly-executables',
    trackId: 'os14-reverse-engineering',
    title:
      'Bố Cục Bộ Nhớ Tiến Trình C/C++, Khung Ngăn Xếp, Đống Bộ Nhớ & Quy Ước Gọi Hàm',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os14-l131-x86-64-and-arm64-assembly-architecture': {
    id: 'os14-l131-x86-64-and-arm64-assembly-architecture',
    slug: 'x86-64-and-arm64-assembly-architecture',
    moduleId: 'os14-m01-memory-assembly-executables',
    trackId: 'os14-reverse-engineering',
    title:
      'Kiến Trúc Tập Lệnh Hợp Ngữ x86-64 & ARM64 (AArch64): Thanh Ghi, Cờ Hiệu & Chế Độ Định Địa Chỉ',
    runtimeMode: 'decision-lab',
    prerequisites: ['os14-l130-memory-layout-stack-heap-and-calling-conventions'],
    validationStatus: 'unverified',
  },
  'os14-l132-executable-formats-elf-pe-macho-and-symbols': {
    id: 'os14-l132-executable-formats-elf-pe-macho-and-symbols',
    slug: 'executable-formats-elf-pe-macho-and-symbols',
    moduleId: 'os14-m01-memory-assembly-executables',
    trackId: 'os14-reverse-engineering',
    title:
      'Giải Phẫu Định Dạng Tập Tin Thực Thi: ELF, PE/COFF, Mach-O & Cơ Chế Phân Giải Ký Hiệu',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os14-l130-memory-layout-stack-heap-and-calling-conventions',
      'os14-l131-x86-64-and-arm64-assembly-architecture',
    ],
    validationStatus: 'unverified',
  },
  'os14-l136-stack-buffer-overflows-and-control-flow-hijacking': {
    id: 'os14-l136-stack-buffer-overflows-and-control-flow-hijacking',
    slug: 'stack-buffer-overflows-and-control-flow-hijacking',
    moduleId: 'os14-m03-memory-failures-and-mitigations',
    trackId: 'os14-reverse-engineering',
    title:
      'Tràn Bộ Đệm Ngăn Xếp (Stack Overflow), Ghi Đè Con Trỏ RIP & Chiếm Quyền Thực Thi',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os14-l137-exploit-mitigations-dep-nx-aslr-canaries-and-cet': {
    id: 'os14-l137-exploit-mitigations-dep-nx-aslr-canaries-and-cet',
    slug: 'exploit-mitigations-dep-nx-aslr-canaries-and-cet',
    moduleId: 'os14-m03-memory-failures-and-mitigations',
    trackId: 'os14-reverse-engineering',
    title:
      'Các Cơ Chế Giảm Thiểu Khai Thác Hiện Đại: DEP/NX, ASLR, Stack Canaries & Intel CET',
    runtimeMode: 'decision-lab',
    prerequisites: ['os14-l136-stack-buffer-overflows-and-control-flow-hijacking'],
    validationStatus: 'unverified',
  },
  'os14-l138-return-oriented-programming-and-reverse-engineering-capstone': {
    id: 'os14-l138-return-oriented-programming-and-reverse-engineering-capstone',
    slug: 'return-oriented-programming-and-reverse-engineering-capstone',
    moduleId: 'os14-m03-memory-failures-and-mitigations',
    trackId: 'os14-reverse-engineering',
    title:
      'Kỹ Thuật Tái Sử Dụng Mã Lệnh (ROP Chain), Stack Pivoting & Bài Tập Capstone Dịch Ngược',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os14-l136-stack-buffer-overflows-and-control-flow-hijacking',
      'os14-l137-exploit-mitigations-dep-nx-aslr-canaries-and-cet',
    ],
    validationStatus: 'unverified',
  },
  'os14-l133-disassembly-and-decompilation-with-ghidra-and-ida': {
    id: 'os14-l133-disassembly-and-decompilation-with-ghidra-and-ida',
    slug: 'disassembly-and-decompilation-with-ghidra-and-ida',
    moduleId: 'os14-m02-static-dynamic-debugging',
    trackId: 'os14-reverse-engineering',
    title:
      'Tháo Gỡ Hợp Ngữ Tĩnh & Dịch Ngược Decompilation Chuyên Sâu với Ghidra và IDA Pro',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os14-l134-dynamic-analysis-and-tracing-with-gdb-and-frida': {
    id: 'os14-l134-dynamic-analysis-and-tracing-with-gdb-and-frida',
    slug: 'dynamic-analysis-and-tracing-with-gdb-and-frida',
    moduleId: 'os14-m02-static-dynamic-debugging',
    trackId: 'os14-reverse-engineering',
    title:
      'Gỡ Lỗi Động & Tracing Tiến Trình Runtime với GDB/GEF và Frida Instrumentation',
    runtimeMode: 'decision-lab',
    prerequisites: ['os14-l133-disassembly-and-decompilation-with-ghidra-and-ida'],
    validationStatus: 'unverified',
  },
  'os14-l135-anti-debugging-obfuscation-and-binary-unpacking': {
    id: 'os14-l135-anti-debugging-obfuscation-and-binary-unpacking',
    slug: 'anti-debugging-obfuscation-and-binary-unpacking',
    moduleId: 'os14-m02-static-dynamic-debugging',
    trackId: 'os14-reverse-engineering',
    title:
      'Nhận Diện Kỹ Thuật Chống Gỡ Lỗi (Anti-Debugging), Làm Rối Mã & Unpacking Nhị Phân',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os14-l133-disassembly-and-decompilation-with-ghidra-and-ida',
      'os14-l134-dynamic-analysis-and-tracing-with-gdb-and-frida',
    ],
    validationStatus: 'unverified',
  },
  'os15-l139-malware-classification-and-behavioral-triage': {
    id: 'os15-l139-malware-classification-and-behavioral-triage',
    slug: 'malware-classification-and-behavioral-triage',
    moduleId: 'os15-m01-malware-behavior-analysis',
    trackId: 'os15-malware-c2-emulation',
    title: 'Phân Loại Mã Độc & Quy Trình Tiếp Nhận Đánh Giá Hành Vi Sơ Bộ',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os15-l140-sandbox-instrumentation-and-api-monitoring': {
    id: 'os15-l140-sandbox-instrumentation-and-api-monitoring',
    slug: 'sandbox-instrumentation-and-api-monitoring',
    moduleId: 'os15-m01-malware-behavior-analysis',
    trackId: 'os15-malware-c2-emulation',
    title: 'Hạ Tầng Giám Sát Hộp Cát Sandbox, Thu Thập Hành Vi API & Kernel Callbacks',
    runtimeMode: 'decision-lab',
    prerequisites: ['os15-l139-malware-classification-and-behavioral-triage'],
    validationStatus: 'unverified',
  },
  'os15-l141-evasion-techniques-and-sandbox-detection': {
    id: 'os15-l141-evasion-techniques-and-sandbox-detection',
    slug: 'evasion-techniques-and-sandbox-detection',
    moduleId: 'os15-m01-malware-behavior-analysis',
    trackId: 'os15-malware-c2-emulation',
    title:
      'Kỹ Thuật Né Tránh Phân Tích, Nhận Diện Môi Trường Ảo Hóa & Chiến Lược Đánh Lừa',
    runtimeMode: 'decision-lab',
    prerequisites: [
      'os15-l139-malware-classification-and-behavioral-triage',
      'os15-l140-sandbox-instrumentation-and-api-monitoring',
    ],
    validationStatus: 'unverified',
  },
};

/**
 * Resolves a lesson descriptor from the canonical registry.
 * Fails closed: returns undefined if not registered, ensuring no heuristic fallback.
 */
export function getLessonDescriptor(lessonId: string): LessonDescriptor | undefined {
  return CANONICAL_LESSON_REGISTRY[lessonId];
}

/**
 * Checks whether a lesson has met all release gates for 'validated' status.
 */
export function isLessonValidated(lessonId: string): boolean {
  return CANONICAL_LESSON_REGISTRY[lessonId]?.validationStatus === 'validated';
}
