/**
 * ============================================================================
 * OFFENSIVE SECURITY ACADEMY - CANONICAL LESSON REGISTRY (v3.1)
 * ============================================================================
 * Programmatically derived from data/academy JSONs and curriculum-manifest.json.
 * 100% manifest parity: 27 modules / 81 lessons.
 * All lessons currently hold unverified status awaiting individual contract certification.
 */

import type { RuntimeMode } from '../types/contract';

export interface LessonDescriptor {
  id: string;
  slug: string;
  moduleId: string;
  trackId: string;
  title: string;
  runtimeMode: RuntimeMode;
  prerequisites: string[];
  validationStatus: 'draft' | 'unverified' | 'validated';
  contractVersion?: 'v3.0';
}

export const CANONICAL_LESSON_REGISTRY: Record<string, LessonDescriptor> = {
  'os00-l07-evidence-collection-and-chain-of-custody': {
    id: 'os00-l07-evidence-collection-and-chain-of-custody',
    slug: 'evidence-collection-and-chain-of-custody',
    moduleId: 'os00-m03-evidence-and-disclosure',
    trackId: 'os00-ethics-authorization',
    title: 'Thu thập Bằng chứng Kỹ thuật & Chuỗi Hành trình (Chain of Custody)',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os00-l08-sensitive-data-handling-and-redaction': {
    id: 'os00-l08-sensitive-data-handling-and-redaction',
    slug: 'sensitive-data-handling-and-redaction',
    moduleId: 'os00-m03-evidence-and-disclosure',
    trackId: 'os00-ethics-authorization',
    title: 'Xử lý Dữ liệu Nhạy cảm, Che mờ (Redaction) & Lưu trữ An toàn',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l07-evidence-collection-and-chain-of-custody'],
    validationStatus: 'unverified',
  },
  'os00-l09-coordinated-vulnerability-disclosure': {
    id: 'os00-l09-coordinated-vulnerability-disclosure',
    slug: 'coordinated-vulnerability-disclosure',
    moduleId: 'os00-m03-evidence-and-disclosure',
    trackId: 'os00-ethics-authorization',
    title: 'Quy trình Công bố Lỗ hổng Phối hợp (CVD) & Quản trị Rủi ro',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l08-sensitive-data-handling-and-redaction'],
    validationStatus: 'unverified',
  },
  'os00-l01-offensive-work-map': {
    id: 'os00-l01-offensive-work-map',
    slug: 'offensive-work-map',
    moduleId: 'os00-m01-roles-and-boundaries',
    trackId: 'os00-ethics-authorization',
    title: 'Bản đồ nghề Offensive Security',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os00-l02-authority-before-capability': {
    id: 'os00-l02-authority-before-capability',
    slug: 'authority-before-capability',
    moduleId: 'os00-m01-roles-and-boundaries',
    trackId: 'os00-ethics-authorization',
    title: 'Authority trước Capability',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l01-offensive-work-map'],
    validationStatus: 'unverified',
  },
  'os00-l03-safe-harbor-decision': {
    id: 'os00-l03-safe-harbor-decision',
    slug: 'safe-harbor-decision',
    moduleId: 'os00-m01-roles-and-boundaries',
    trackId: 'os00-ethics-authorization',
    title: 'Safe Harbor không phải giấy phép vô hạn',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l02-authority-before-capability'],
    validationStatus: 'unverified',
  },
  'os00-l04-scoping-boundaries-and-dependencies': {
    id: 'os00-l04-scoping-boundaries-and-dependencies',
    slug: 'scoping-boundaries-and-dependencies',
    moduleId: 'os00-m02-rules-of-engagement',
    trackId: 'os00-ethics-authorization',
    title: 'Thiết lập Phạm vi (Scope) & Ranh giới Phụ thuộc Bên thứ ba',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os00-l05-rules-of-engagement-and-stop-conditions': {
    id: 'os00-l05-rules-of-engagement-and-stop-conditions',
    slug: 'rules-of-engagement-and-stop-conditions',
    moduleId: 'os00-m02-rules-of-engagement',
    trackId: 'os00-ethics-authorization',
    title: 'Xây dựng Rules of Engagement & Điều kiện Dừng Khẩn cấp',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l04-scoping-boundaries-and-dependencies'],
    validationStatus: 'unverified',
  },
  'os00-l06-deconfliction-and-operational-logging': {
    id: 'os00-l06-deconfliction-and-operational-logging',
    slug: 'deconfliction-and-operational-logging',
    moduleId: 'os00-m02-rules-of-engagement',
    trackId: 'os00-ethics-authorization',
    title: 'Quy trình Deconfliction, Phối hợp Tác chiến & Nhật ký Audit',
    runtimeMode: 'decision-lab',
    prerequisites: ['os00-l05-rules-of-engagement-and-stop-conditions'],
    validationStatus: 'unverified',
  },
  'os01-l07-dns-resolution-and-dhcp-boundaries': {
    id: 'os01-l07-dns-resolution-and-dhcp-boundaries',
    slug: 'dns-resolution-and-dhcp-boundaries',
    moduleId: 'os01-m03-dns-transport-and-tls',
    trackId: 'os01-network-foundations',
    title: 'Phân giải DNS Phân cấp & Ranh giới Tin cậy DHCP',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l08-tcp-udp-transport-state': {
    id: 'os01-l08-tcp-udp-transport-state',
    slug: 'tcp-udp-transport-state',
    moduleId: 'os01-m03-dns-transport-and-tls',
    trackId: 'os01-network-foundations',
    title: 'Trạng Thái Transport: TCP Handshake, UDP & Khai thác Trạng thái',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l07-dns-resolution-and-dhcp-boundaries'],
    validationStatus: 'unverified',
  },
  'os01-l09-http-tls-trust-boundaries': {
    id: 'os01-l09-http-tls-trust-boundaries',
    slug: 'http-tls-trust-boundaries',
    moduleId: 'os01-m03-dns-transport-and-tls',
    trackId: 'os01-network-foundations',
    title: 'HTTP Semantics & Ranh giới Tin cậy TLS',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l08-tcp-udp-transport-state'],
    validationStatus: 'unverified',
  },
  'os01-l10-smb-ldap-enterprise-protocols': {
    id: 'os01-l10-smb-ldap-enterprise-protocols',
    slug: 'smb-ldap-enterprise-protocols',
    moduleId: 'os01-m04-enterprise-protocols-and-packets',
    trackId: 'os01-network-foundations',
    title: 'SMB & LDAP: Giao thức Chia sẻ và Thư mục của Doanh nghiệp',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l11-packet-capture-methodology': {
    id: 'os01-l11-packet-capture-methodology',
    slug: 'packet-capture-methodology',
    moduleId: 'os01-m04-enterprise-protocols-and-packets',
    trackId: 'os01-network-foundations',
    title: 'Bắt & Phân tích Gói tin: Phương pháp Có kỷ luật',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l10-smb-ldap-enterprise-protocols'],
    validationStatus: 'unverified',
  },
  'os01-l12-topology-reasoning-from-evidence': {
    id: 'os01-l12-topology-reasoning-from-evidence',
    slug: 'topology-reasoning-from-evidence',
    moduleId: 'os01-m04-enterprise-protocols-and-packets',
    trackId: 'os01-network-foundations',
    title: 'Suy luận Topology: Dựng Bản đồ Mạng từ Bằng chứng',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l11-packet-capture-methodology'],
    validationStatus: 'unverified',
  },
  'os01-l04-ethernet-and-arp-trust-boundary': {
    id: 'os01-l04-ethernet-and-arp-trust-boundary',
    slug: 'ethernet-and-arp-trust-boundary',
    moduleId: 'os01-m02-link-routing-and-segmentation',
    trackId: 'os01-network-foundations',
    title: 'Ethernet Frame, Bảng MAC của Switch & Ranh giới Tin cậy ARP',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l05-ip-routing-and-nat-boundaries': {
    id: 'os01-l05-ip-routing-and-nat-boundaries',
    slug: 'ip-routing-and-nat-boundaries',
    moduleId: 'os01-m02-link-routing-and-segmentation',
    trackId: 'os01-network-foundations',
    title: 'Bảng Định tuyến, Longest Prefix Match & Ranh giới NAT',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l04-ethernet-and-arp-trust-boundary'],
    validationStatus: 'unverified',
  },
  'os01-l06-vlan-vpn-segmentation': {
    id: 'os01-l06-vlan-vpn-segmentation',
    slug: 'vlan-vpn-segmentation',
    moduleId: 'os01-m02-link-routing-and-segmentation',
    trackId: 'os01-network-foundations',
    title: 'Phân Đoạn VLAN, Inter-VLAN Routing & Ranh giới VPN',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l05-ip-routing-and-nat-boundaries'],
    validationStatus: 'unverified',
  },
  'os01-l01-process-memory-and-data-representation': {
    id: 'os01-l01-process-memory-and-data-representation',
    slug: 'process-memory-and-data-representation',
    moduleId: 'os01-m01-processes-data-and-addressing',
    trackId: 'os01-network-foundations',
    title: 'Tiến trình (Process), Bộ nhớ & Biểu diễn Dữ liệu (Hex, Endian, Encoding)',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os01-l02-ipv4-addressing-and-cidr-subnetting': {
    id: 'os01-l02-ipv4-addressing-and-cidr-subnetting',
    slug: 'ipv4-addressing-and-cidr-subnetting',
    moduleId: 'os01-m01-processes-data-and-addressing',
    trackId: 'os01-network-foundations',
    title: 'Địa chỉ IPv4, Phân lớp Mạng & Kỹ thuật Chia mạng con CIDR',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l01-process-memory-and-data-representation'],
    validationStatus: 'unverified',
  },
  'os01-l03-ipv6-foundations-and-dual-stack-boundaries': {
    id: 'os01-l03-ipv6-foundations-and-dual-stack-boundaries',
    slug: 'ipv6-foundations-and-dual-stack-boundaries',
    moduleId: 'os01-m01-processes-data-and-addressing',
    trackId: 'os01-network-foundations',
    title: 'Nền tảng IPv6, Ranh giới Dual-Stack & Bẫy Cấu hình An ninh',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os01-l02-ipv4-addressing-and-cidr-subnetting'],
    validationStatus: 'unverified',
  },
  'os02-l13-filesystem-hierarchy-and-file-types': {
    id: 'os02-l13-filesystem-hierarchy-and-file-types',
    slug: 'filesystem-hierarchy-and-file-types',
    moduleId: 'os02-m01-files-identity-permissions',
    trackId: 'os02-linux-foundations',
    title: 'Cây Filesystem, Inode & Các Loại File',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os02-l14-users-groups-and-identity-boundaries': {
    id: 'os02-l14-users-groups-and-identity-boundaries',
    slug: 'users-groups-and-identity-boundaries',
    moduleId: 'os02-m01-files-identity-permissions',
    trackId: 'os02-linux-foundations',
    title: 'UID/GID, /etc/passwd–shadow & Ranh giới root/sudo',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l13-filesystem-hierarchy-and-file-types'],
    validationStatus: 'unverified',
  },
  'os02-l15-permission-bits-and-special-modes': {
    id: 'os02-l15-permission-bits-and-special-modes',
    slug: 'permission-bits-and-special-modes',
    moduleId: 'os02-m01-files-identity-permissions',
    trackId: 'os02-linux-foundations',
    title: 'Permission Bits, Umask & SUID/SGID/Sticky',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l14-users-groups-and-identity-boundaries'],
    validationStatus: 'unverified',
  },
  'os02-l19-linux-capabilities-and-suid-privesc': {
    id: 'os02-l19-linux-capabilities-and-suid-privesc',
    slug: 'linux-capabilities-and-suid-privesc',
    moduleId: 'os02-m03-linux-boundaries-and-telemetry',
    trackId: 'os02-linux-foundations',
    title: 'Linux Capabilities, SUID & Privilege Boundaries',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os02-l20-namespaces-cgroups-container-boundaries': {
    id: 'os02-l20-namespaces-cgroups-container-boundaries',
    slug: 'namespaces-cgroups-container-boundaries',
    moduleId: 'os02-m03-linux-boundaries-and-telemetry',
    trackId: 'os02-linux-foundations',
    title: 'Namespaces, Cgroups & Container Boundary Escapes',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l19-linux-capabilities-and-suid-privesc'],
    validationStatus: 'unverified',
  },
  'os02-l21-auditd-ebpf-and-host-telemetry': {
    id: 'os02-l21-auditd-ebpf-and-host-telemetry',
    slug: 'auditd-ebpf-and-host-telemetry',
    moduleId: 'os02-m03-linux-boundaries-and-telemetry',
    trackId: 'os02-linux-foundations',
    title: 'Auditd, eBPF & Linux Host Telemetry',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l20-namespaces-cgroups-container-boundaries'],
    validationStatus: 'unverified',
  },
  'os02-l16-processes-signals-and-procfs': {
    id: 'os02-l16-processes-signals-and-procfs',
    slug: 'processes-signals-and-procfs',
    moduleId: 'os02-m02-processes-services-shell',
    trackId: 'os02-linux-foundations',
    title: 'Process Tree, Signals & /proc',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os02-l17-systemd-units-and-journal': {
    id: 'os02-l17-systemd-units-and-journal',
    slug: 'systemd-units-and-journal',
    moduleId: 'os02-m02-processes-services-shell',
    trackId: 'os02-linux-foundations',
    title: 'systemd Units, Hardening Directives & Journal',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l16-processes-signals-and-procfs'],
    validationStatus: 'unverified',
  },
  'os02-l18-packages-cron-and-shell-env': {
    id: 'os02-l18-packages-cron-and-shell-env',
    slug: 'packages-cron-and-shell-env',
    moduleId: 'os02-m02-processes-services-shell',
    trackId: 'os02-linux-foundations',
    title: 'Package Integrity, Cron & Shell Environment',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os02-l17-systemd-units-and-journal'],
    validationStatus: 'unverified',
  },
  'os03-l22-defender-av-edr-and-amsi': {
    id: 'os03-l22-defender-av-edr-and-amsi',
    slug: 'defender-av-edr-and-amsi',
    moduleId: 'os03-m03-endpoint-controls-and-events',
    trackId: 'os03-windows-foundations',
    title: 'Microsoft Defender, ASR & AMSI Architecture',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os03-l23-windows-firewall-and-network-boundaries': {
    id: 'os03-l23-windows-firewall-and-network-boundaries',
    slug: 'windows-firewall-and-network-boundaries',
    moduleId: 'os03-m03-endpoint-controls-and-events',
    trackId: 'os03-windows-foundations',
    title: 'Windows Firewall & Host Network Boundaries',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l22-defender-av-edr-and-amsi'],
    validationStatus: 'unverified',
  },
  'os03-l24-security-event-log-and-sysmon-telemetry': {
    id: 'os03-l24-security-event-log-and-sysmon-telemetry',
    slug: 'security-event-log-and-sysmon-telemetry',
    moduleId: 'os03-m03-endpoint-controls-and-events',
    trackId: 'os03-windows-foundations',
    title: 'Windows Event Logs, Sysmon & Telemetry Engineering',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l23-windows-firewall-and-network-boundaries'],
    validationStatus: 'unverified',
  },
  'os03-l19-services-scm-and-path-security': {
    id: 'os03-l19-services-scm-and-path-security',
    slug: 'services-scm-and-path-security',
    moduleId: 'os03-m02-services-powershell-remote',
    trackId: 'os03-windows-foundations',
    title: 'SCM, Service Registry & Path Security',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os03-l20-scheduled-tasks-and-autoruns': {
    id: 'os03-l20-scheduled-tasks-and-autoruns',
    slug: 'scheduled-tasks-and-autoruns',
    moduleId: 'os03-m02-services-powershell-remote',
    trackId: 'os03-windows-foundations',
    title: 'Task Scheduler & Bản đồ Autoruns',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l19-services-scm-and-path-security'],
    validationStatus: 'unverified',
  },
  'os03-l21-powershell-logging-and-remote-admin': {
    id: 'os03-l21-powershell-logging-and-remote-admin',
    slug: 'powershell-logging-and-remote-admin',
    moduleId: 'os03-m02-services-powershell-remote',
    trackId: 'os03-windows-foundations',
    title: 'PowerShell Logging, Execution Policy & WinRM/JEA',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l20-scheduled-tasks-and-autoruns'],
    validationStatus: 'unverified',
  },
  'os03-l16-windows-architecture-and-principals': {
    id: 'os03-l16-windows-architecture-and-principals',
    slug: 'windows-architecture-and-principals',
    moduleId: 'os03-m01-architecture-identities-acls',
    trackId: 'os03-windows-foundations',
    title: 'Kiến trúc Windows & Security Principals (SID)',
    runtimeMode: 'telemetry-inspector',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os03-l17-access-tokens-and-uac': {
    id: 'os03-l17-access-tokens-and-uac',
    slug: 'access-tokens-and-uac',
    moduleId: 'os03-m01-architecture-identities-acls',
    trackId: 'os03-windows-foundations',
    title: 'Access Token & UAC Filtered Token',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l16-windows-architecture-and-principals'],
    validationStatus: 'unverified',
  },
  'os03-l18-acls-and-permission-evaluation': {
    id: 'os03-l18-acls-and-permission-evaluation',
    slug: 'acls-and-permission-evaluation',
    moduleId: 'os03-m01-architecture-identities-acls',
    trackId: 'os03-windows-foundations',
    title: 'Security Descriptor, DACL & Thứ tự Đánh giá ACE',
    runtimeMode: 'telemetry-inspector',
    prerequisites: ['os03-l17-access-tokens-and-uac'],
    validationStatus: 'unverified',
  },
  'os04-l25-bash-scripting-and-pipeline-safety': {
    id: 'os04-l25-bash-scripting-and-pipeline-safety',
    slug: 'bash-scripting-and-pipeline-safety',
    moduleId: 'os04-m01-bash-python-powershell',
    trackId: 'os04-operator-scripting',
    title: 'Safe Bash Scripting & UNIX Pipeline Engineering',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os04-l26-python-operator-tooling-and-subprocesses': {
    id: 'os04-l26-python-operator-tooling-and-subprocesses',
    slug: 'python-operator-tooling-and-subprocesses',
    moduleId: 'os04-m01-bash-python-powershell',
    trackId: 'os04-operator-scripting',
    title: 'Python Operator Tooling & Safe Subprocess Architecture',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l25-bash-scripting-and-pipeline-safety'],
    validationStatus: 'unverified',
  },
  'os04-l27-powershell-advanced-functions-and-objects': {
    id: 'os04-l27-powershell-advanced-functions-and-objects',
    slug: 'powershell-advanced-functions-and-objects',
    moduleId: 'os04-m01-bash-python-powershell',
    trackId: 'os04-operator-scripting',
    title: 'PowerShell Advanced Functions & Object Pipeline Architecture',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l26-python-operator-tooling-and-subprocesses'],
    validationStatus: 'unverified',
  },
  'os04-l31-concurrency-asyncio-and-worker-pools': {
    id: 'os04-l31-concurrency-asyncio-and-worker-pools',
    slug: 'concurrency-asyncio-and-worker-pools',
    moduleId: 'os04-m03-safe-evidence-automation',
    trackId: 'os04-operator-scripting',
    title: 'Bounded Concurrency, AsyncIO & Worker Pool Engineering',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os04-l32-defensive-error-handling-and-telemetry-pipelines': {
    id: 'os04-l32-defensive-error-handling-and-telemetry-pipelines',
    slug: 'defensive-error-handling-and-telemetry-pipelines',
    moduleId: 'os04-m03-safe-evidence-automation',
    trackId: 'os04-operator-scripting',
    title: 'Defensive Error Architecture & Observable Telemetry Pipelines',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l31-concurrency-asyncio-and-worker-pools'],
    validationStatus: 'unverified',
  },
  'os04-l33-evidence-collector-capstone-and-safe-packaging': {
    id: 'os04-l33-evidence-collector-capstone-and-safe-packaging',
    slug: 'evidence-collector-capstone-and-safe-packaging',
    moduleId: 'os04-m03-safe-evidence-automation',
    trackId: 'os04-operator-scripting',
    title: 'Safe Operator CLI Packaging & Evidence Collector Capstone',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l32-defensive-error-handling-and-telemetry-pipelines'],
    validationStatus: 'unverified',
  },
  'os04-l28-regular-expressions-and-text-normalization': {
    id: 'os04-l28-regular-expressions-and-text-normalization',
    slug: 'regular-expressions-and-text-normalization',
    moduleId: 'os04-m02-structured-data-http-git',
    trackId: 'os04-operator-scripting',
    title: 'Deterministic Regular Expressions & Telemetry Normalization',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os04-l29-structured-data-json-yaml-csv-parsing': {
    id: 'os04-l29-structured-data-json-yaml-csv-parsing',
    slug: 'structured-data-json-yaml-csv-parsing',
    moduleId: 'os04-m02-structured-data-http-git',
    trackId: 'os04-operator-scripting',
    title: 'Type-Safe Data Serialization: JSON, YAML & CSV Ingestion',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l28-regular-expressions-and-text-normalization'],
    validationStatus: 'unverified',
  },
  'os04-l30-http-clients-and-git-automation': {
    id: 'os04-l30-http-clients-and-git-automation',
    slug: 'http-clients-and-git-automation',
    moduleId: 'os04-m02-structured-data-http-git',
    trackId: 'os04-operator-scripting',
    title: 'Resilient HTTP Clients & Secure Git Evidence Automation',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os04-l29-structured-data-json-yaml-csv-parsing'],
    validationStatus: 'unverified',
  },
  'os05-l34-penetration-testing-standards-and-planning': {
    id: 'os05-l34-penetration-testing-standards-and-planning',
    slug: 'penetration-testing-standards-and-planning',
    moduleId: 'os05-m01-engagement-recon-enumeration',
    trackId: 'os05-pentest-methodology',
    title: 'Penetration Testing Frameworks, Scoping & Pre-Engagement Planning',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os05-l35-passive-reconnaissance-and-osint-methodology': {
    id: 'os05-l35-passive-reconnaissance-and-osint-methodology',
    slug: 'passive-reconnaissance-and-osint-methodology',
    moduleId: 'os05-m01-engagement-recon-enumeration',
    trackId: 'os05-pentest-methodology',
    title: 'Passive Reconnaissance, OSINT & Attack Surface Discovery',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l34-penetration-testing-standards-and-planning'],
    validationStatus: 'unverified',
  },
  'os05-l36-active-enumeration-and-service-fingerprinting': {
    id: 'os05-l36-active-enumeration-and-service-fingerprinting',
    slug: 'active-enumeration-and-service-fingerprinting',
    moduleId: 'os05-m01-engagement-recon-enumeration',
    trackId: 'os05-pentest-methodology',
    title: 'Active Enumeration, Service Fingerprinting & Protocol Discovery',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l35-passive-reconnaissance-and-osint-methodology'],
    validationStatus: 'unverified',
  },
  'os05-l40-technical-vulnerability-reporting-and-structure': {
    id: 'os05-l40-technical-vulnerability-reporting-and-structure',
    slug: 'technical-vulnerability-reporting-and-structure',
    moduleId: 'os05-m03-report-remediation-retest',
    trackId: 'os05-pentest-methodology',
    title: 'Professional Vulnerability Reporting & Finding Structure',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os05-l41-root-cause-analysis-and-defense-in-depth-remediation': {
    id: 'os05-l41-root-cause-analysis-and-defense-in-depth-remediation',
    slug: 'root-cause-analysis-and-defense-in-depth-remediation',
    moduleId: 'os05-m03-report-remediation-retest',
    trackId: 'os05-pentest-methodology',
    title: 'Root-Cause Remediation, Defense-in-Depth & Strategic Guidance',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l40-technical-vulnerability-reporting-and-structure'],
    validationStatus: 'unverified',
  },
  'os05-l42-remediation-verification-and-retesting-workflows': {
    id: 'os05-l42-remediation-verification-and-retesting-workflows',
    slug: 'remediation-verification-and-retesting-workflows',
    moduleId: 'os05-m03-report-remediation-retest',
    trackId: 'os05-pentest-methodology',
    title: 'Remediation Verification, Retesting Workflows & Engagement Closeout',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l41-root-cause-analysis-and-defense-in-depth-remediation'],
    validationStatus: 'unverified',
  },
  'os05-l37-vulnerability-analysis-and-false-positive-triaging': {
    id: 'os05-l37-vulnerability-analysis-and-false-positive-triaging',
    slug: 'vulnerability-analysis-and-false-positive-triaging',
    moduleId: 'os05-m02-verification-impact-evidence',
    trackId: 'os05-pentest-methodology',
    title: 'Vulnerability Analysis, CVE Mapping & False-Positive Triaging',
    runtimeMode: 'decision-lab',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os05-l38-controlled-exploitation-and-proof-of-concept': {
    id: 'os05-l38-controlled-exploitation-and-proof-of-concept',
    slug: 'controlled-exploitation-and-proof-of-concept',
    moduleId: 'os05-m02-verification-impact-evidence',
    trackId: 'os05-pentest-methodology',
    title: 'Controlled Exploitation, Safe Proof of Concept & Blast Radius Management',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l37-vulnerability-analysis-and-false-positive-triaging'],
    validationStatus: 'unverified',
  },
  'os05-l39-business-impact-demonstration-and-evidence-chain': {
    id: 'os05-l39-business-impact-demonstration-and-evidence-chain',
    slug: 'business-impact-demonstration-and-evidence-chain',
    moduleId: 'os05-m02-verification-impact-evidence',
    trackId: 'os05-pentest-methodology',
    title: 'Business Impact Modeling, Data Redaction & Forensic Evidence Sealing',
    runtimeMode: 'decision-lab',
    prerequisites: ['os05-l38-controlled-exploitation-and-proof-of-concept'],
    validationStatus: 'unverified',
  },
  'os06-l49-blind-network-reconnaissance-and-initial-foothold': {
    id: 'os06-l49-blind-network-reconnaissance-and-initial-foothold',
    slug: 'blind-network-reconnaissance-and-initial-foothold',
    moduleId: 'os06-m03-blind-enterprise-network',
    trackId: 'os06-network-infrastructure',
    title: 'Blind Network Triage, Passive Discovery & Initial Foothold Acquisition',
    runtimeMode: 'browser-demo',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os06-l50-multi-tier-lateral-movement-and-privilege-chains': {
    id: 'os06-l50-multi-tier-lateral-movement-and-privilege-chains',
    slug: 'multi-tier-lateral-movement-and-privilege-chains',
    moduleId: 'os06-m03-blind-enterprise-network',
    trackId: 'os06-network-infrastructure',
    title: 'Multi-Tier Lateral Movement & Enterprise Privilege Chaining',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l49-blind-network-reconnaissance-and-initial-foothold'],
    validationStatus: 'unverified',
  },
  'os06-l51-comprehensive-infrastructure-audit-and-reporting': {
    id: 'os06-l51-comprehensive-infrastructure-audit-and-reporting',
    slug: 'comprehensive-infrastructure-audit-and-reporting',
    moduleId: 'os06-m03-blind-enterprise-network',
    trackId: 'os06-network-infrastructure',
    title: 'Enterprise Attack Path Mapping, Remediation & Executive Debrief',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l50-multi-tier-lateral-movement-and-privilege-chains'],
    validationStatus: 'unverified',
  },
  'os06-l43-enterprise-network-discovery-and-smb-rpc-enumeration': {
    id: 'os06-l43-enterprise-network-discovery-and-smb-rpc-enumeration',
    slug: 'enterprise-network-discovery-and-smb-rpc-enumeration',
    moduleId: 'os06-m01-discovery-services-authentication',
    trackId: 'os06-network-infrastructure',
    title: 'Enterprise Network Discovery & SMB/RPC Protocol Interrogation',
    runtimeMode: 'browser-demo',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os06-l44-common-infrastructure-services-and-misconfigurations': {
    id: 'os06-l44-common-infrastructure-services-and-misconfigurations',
    slug: 'common-infrastructure-services-and-misconfigurations',
    moduleId: 'os06-m01-discovery-services-authentication',
    trackId: 'os06-network-infrastructure',
    title: 'Common Infrastructure Services & Misconfiguration Auditing',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l43-enterprise-network-discovery-and-smb-rpc-enumeration'],
    validationStatus: 'unverified',
  },
  'os06-l45-authentication-weaknesses-and-credential-auditing': {
    id: 'os06-l45-authentication-weaknesses-and-credential-auditing',
    slug: 'authentication-weaknesses-and-credential-auditing',
    moduleId: 'os06-m01-discovery-services-authentication',
    trackId: 'os06-network-infrastructure',
    title: 'Authentication Weaknesses & Credential Spraying Safety',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l44-common-infrastructure-services-and-misconfigurations'],
    validationStatus: 'unverified',
  },
  'os06-l46-host-privilege-boundaries-and-session-security': {
    id: 'os06-l46-host-privilege-boundaries-and-session-security',
    slug: 'host-privilege-boundaries-and-session-security',
    moduleId: 'os06-m02-host-boundaries-and-movement',
    trackId: 'os06-network-infrastructure',
    title: 'Host Privilege Boundaries & Interactive Session Containment',
    runtimeMode: 'browser-demo',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os06-l47-ssh-and-socks-pivoting-port-forwarding': {
    id: 'os06-l47-ssh-and-socks-pivoting-port-forwarding',
    slug: 'ssh-and-socks-pivoting-port-forwarding',
    moduleId: 'os06-m02-host-boundaries-and-movement',
    trackId: 'os06-network-infrastructure',
    title: 'Multi-Tier Tunneling, SOCKS Proxies & Lateral Pivoting',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l46-host-privilege-boundaries-and-session-security'],
    validationStatus: 'unverified',
  },
  'os06-l48-network-segmentation-testing-and-telemetry-evasion': {
    id: 'os06-l48-network-segmentation-testing-and-telemetry-evasion',
    slug: 'network-segmentation-testing-and-telemetry-evasion',
    moduleId: 'os06-m02-host-boundaries-and-movement',
    trackId: 'os06-network-infrastructure',
    title: 'Network Segmentation Validation & Defensive Telemetry Analysis',
    runtimeMode: 'browser-demo',
    prerequisites: ['os06-l47-ssh-and-socks-pivoting-port-forwarding'],
    validationStatus: 'unverified',
  },
  'os07-l55-broken-object-level-and-function-authorization': {
    id: 'os07-l55-broken-object-level-and-function-authorization',
    slug: 'broken-object-level-and-function-authorization',
    moduleId: 'os07-m02-access-control-and-injection',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Broken Object & Function Level Authorization (BOLA/IDOR & BFLA)',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l56-cross-site-scripting-and-context-encoding': {
    id: 'os07-l56-cross-site-scripting-and-context-encoding',
    slug: 'cross-site-scripting-and-context-encoding',
    moduleId: 'os07-m02-access-control-and-injection',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Cross-Site Scripting (XSS), Contextual Encoding & Content Security Policy',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l55-broken-object-level-and-function-authorization'],
    validationStatus: 'unverified',
  },
  'os07-l57-sql-nosql-command-and-template-injection': {
    id: 'os07-l57-sql-nosql-command-and-template-injection',
    slug: 'sql-nosql-command-and-template-injection',
    moduleId: 'os07-m02-access-control-and-injection',
    trackId: 'os07-web-api-bug-bounty',
    title: 'SQL, NoSQL, OS Command & Server-Side Template Injection (SSTI)',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l56-cross-site-scripting-and-context-encoding'],
    validationStatus: 'unverified',
  },
  'os07-l64-bug-bounty-reconnaissance-and-asset-mapping': {
    id: 'os07-l64-bug-bounty-reconnaissance-and-asset-mapping',
    slug: 'bug-bounty-reconnaissance-and-asset-mapping',
    moduleId: 'os07-m05-bounty-recon-report-disclosure',
    trackId: 'os07-web-api-bug-bounty',
    title: 'External Attack Surface Management & Bug Bounty Reconnaissance',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l65-vulnerability-triage-and-cvss-v4-impact': {
    id: 'os07-l65-vulnerability-triage-and-cvss-v4-impact',
    slug: 'vulnerability-triage-and-cvss-v4-impact',
    moduleId: 'os07-m05-bounty-recon-report-disclosure',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Vulnerability Triage, CVSS v4.0 Calculation & Impact Demonstration',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l64-bug-bounty-reconnaissance-and-asset-mapping'],
    validationStatus: 'unverified',
  },
  'os07-l66-responsible-disclosure-and-platform-etiquette': {
    id: 'os07-l66-responsible-disclosure-and-platform-etiquette',
    slug: 'responsible-disclosure-and-platform-etiquette',
    moduleId: 'os07-m05-bounty-recon-report-disclosure',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Coordinated Vulnerability Disclosure (CVD), Safe Harbor & Ethics',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l65-vulnerability-triage-and-cvss-v4-impact'],
    validationStatus: 'unverified',
  },
  'os07-l58-cors-misconfigurations-and-csrf-defenses': {
    id: 'os07-l58-cors-misconfigurations-and-csrf-defenses',
    slug: 'cors-misconfigurations-and-csrf-defenses',
    moduleId: 'os07-m03-browser-cross-origin-and-files',
    trackId: 'os07-web-api-bug-bounty',
    title: 'CORS Exploitation, Origin Reflection & Anti-CSRF Architecture',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l59-server-side-request-forgery-and-cloud-metadata': {
    id: 'os07-l59-server-side-request-forgery-and-cloud-metadata',
    slug: 'server-side-request-forgery-and-cloud-metadata',
    moduleId: 'os07-m03-browser-cross-origin-and-files',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Server-Side Request Forgery (SSRF) & Cloud Metadata Exfiltration',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l58-cors-misconfigurations-and-csrf-defenses'],
    validationStatus: 'unverified',
  },
  'os07-l60-file-upload-vulnerabilities-and-path-traversal': {
    id: 'os07-l60-file-upload-vulnerabilities-and-path-traversal',
    slug: 'file-upload-vulnerabilities-and-path-traversal',
    moduleId: 'os07-m03-browser-cross-origin-and-files',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Unrestricted File Uploads, Web Shells & Path Traversal Sanitization',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l59-server-side-request-forgery-and-cloud-metadata'],
    validationStatus: 'unverified',
  },
  'os07-l52-browser-security-model-and-http-semantics': {
    id: 'os07-l52-browser-security-model-and-http-semantics',
    slug: 'browser-security-model-and-http-semantics',
    moduleId: 'os07-m01-browser-http-auth-session',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Browser Security Model, Same-Origin Policy & HTTP Semantics',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l53-authentication-mechanisms-and-password-storage': {
    id: 'os07-l53-authentication-mechanisms-and-password-storage',
    slug: 'authentication-mechanisms-and-password-storage',
    moduleId: 'os07-m01-browser-http-auth-session',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Cryptographic Password Storage & Multi-Factor Authentication',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l52-browser-security-model-and-http-semantics'],
    validationStatus: 'unverified',
  },
  'os07-l54-session-management-cookies-and-token-lifecycles': {
    id: 'os07-l54-session-management-cookies-and-token-lifecycles',
    slug: 'session-management-cookies-and-token-lifecycles',
    moduleId: 'os07-m01-browser-http-auth-session',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Session Security, Cookie Attributes & Token Lifecycles',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l53-authentication-mechanisms-and-password-storage'],
    validationStatus: 'unverified',
  },
  'os07-l61-oauth2-flows-and-jwt-security-mechanics': {
    id: 'os07-l61-oauth2-flows-and-jwt-security-mechanics',
    slug: 'oauth2-flows-and-jwt-security-mechanics',
    moduleId: 'os07-m04-modern-api-and-business-logic',
    trackId: 'os07-web-api-bug-bounty',
    title: 'OAuth 2.0 / OIDC Vulnerabilities & JSON Web Token (JWT) Exploitation',
    runtimeMode: 'webcontainer-node',
    prerequisites: [],
    validationStatus: 'unverified',
  },
  'os07-l62-graphql-introspection-and-websocket-security': {
    id: 'os07-l62-graphql-introspection-and-websocket-security',
    slug: 'graphql-introspection-and-websocket-security',
    moduleId: 'os07-m04-modern-api-and-business-logic',
    trackId: 'os07-web-api-bug-bounty',
    title: 'GraphQL API Security & Cross-Site WebSocket Hijacking (CSWSH)',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l61-oauth2-flows-and-jwt-security-mechanics'],
    validationStatus: 'unverified',
  },
  'os07-l63-race-conditions-and-business-logic-flaws': {
    id: 'os07-l63-race-conditions-and-business-logic-flaws',
    slug: 'race-conditions-and-business-logic-flaws',
    moduleId: 'os07-m04-modern-api-and-business-logic',
    trackId: 'os07-web-api-bug-bounty',
    title: 'Concurrency Race Conditions & Flawed Business Logic Exploitation',
    runtimeMode: 'webcontainer-node',
    prerequisites: ['os07-l62-graphql-introspection-and-websocket-security'],
    validationStatus: 'unverified',
  },
};

/**
 * Resolves a lesson descriptor from the canonical registry.
 * Fails closed: returns undefined if not registered, ensuring no heuristic fallback.
 */
export function getLessonDescriptor(lessonId: string): LessonDescriptor | undefined {
  return CANONICAL_LESSON_REGISTRY[lessonId];
}

/**
 * Checks whether a lesson has met all release gates for 'validated' status.
 */
export function isLessonValidated(lessonId: string): boolean {
  return CANONICAL_LESSON_REGISTRY[lessonId]?.validationStatus === 'validated';
}
